Repository TempleEight/temple, pull requests merged in 2020-04, with the labels that each got.

#203 [service-test] Remove server and server set items from request body
  src/main/scala/temple/test/internal/ServiceTestUtils.scala
Labels: size/M

#207 [go-gen] Add main.go response struct generation
  src/e2e/resources/go/user/user.go.snippet
  src/main/scala/temple/generate/server/go/service/GoServiceGenerator.scala
  src/main/scala/temple/generate/server/go/service/main/GoServiceMainGenerator.scala
  src/main/scala/temple/generate/server/go/service/main/GoServiceMainStructGenerator.scala
  src/test/resources/go/complex-user/complexuser.go.snippet
  src/test/resources/go/simple-user/user.go.snippet
  src/test/scala/temple/generate/server/go/testfiles/match/match.go.snippet
  src/test/scala/temple/generate/server/go/testfiles/user/user.go.snippet
  src/test/scala/temple/testfiles/simple.temple
Labels: size/L

#208 [go-gen][metrics] Generate empty metric.go file
  src/e2e/resources/go/user/metric/metric.go.snippet
  src/e2e/scala/temple/SimpleE2ETest.scala
  src/main/scala/temple/generate/server/go/service/GoServiceGenerator.scala
  src/main/scala/temple/generate/server/go/service/GoServiceMetricGenerator.scala
  src/test/resources/go/complex-user/metric/metric.go.snippet
  src/test/resources/go/simple-user/metric/metric.go.snippet
  src/test/scala/temple/builder/project/ProjectBuilderTest.scala
  src/test/scala/temple/builder/project/ProjectBuilderTestData.scala
  src/test/scala/temple/generate/server/go/GoServiceGeneratorTestData.scala
  src/test/scala/temple/generate/server/go/testfiles/match/metric/metric.go.snippet
  src/test/scala/temple/generate/server/go/testfiles/user/metric/metric.go.snippet
Labels: size/M

#206 [go-gen] Populate validation strings
  src/e2e/resources/go/user/user.go.snippet
  src/main/scala/temple/generate/server/go/service/main/GoServiceMainStructGenerator.scala
  src/test/resources/go/complex-user/complexuser.go.snippet
  src/test/resources/go/simple-user/user.go.snippet
  src/test/scala/temple/generate/server/go/testfiles/match/match.go.snippet
  src/test/scala/temple/generate/server/go/testfiles/user/user.go.snippet
Labels: size/L

#209 [go-gen] Add generation of router, jsonMiddleware and empty handlers to main.go
  src/e2e/resources/go/user/user.go.snippet
  src/main/resources/go/genFiles/common/main/json_middleware.go.snippet
  src/main/scala/temple/generate/server/go/common/GoCommonMainGenerator.scala
  src/main/scala/temple/generate/server/go/service/GoServiceGenerator.scala
  src/main/scala/temple/generate/server/go/service/main/GoServiceMainGenerator.scala
  src/test/resources/go/complex-user/complexuser.go.snippet
  src/test/resources/go/simple-user/user.go.snippet
  src/test/scala/temple/generate/server/go/testfiles/match/match.go.snippet
  src/test/scala/temple/generate/server/go/testfiles/user/user.go.snippet
  src/test/scala/temple/testfiles/simple.temple
Labels: size/L

#210 [Validator] Add decapitalize function
  src/main/scala/temple/utils/StringUtils.scala
  src/test/scala/temple/utils/StringUtilsTest.scala
Labels: size/S

#211 [Validator] Allow metadata to be looked up from struct blocks
  src/main/scala/temple/ast/ServiceBlock.scala
  src/main/scala/temple/ast/TempleBlock.scala
  src/main/scala/temple/ast/TempleNode.scala
  src/main/scala/temple/ast/Templefile.scala
  src/test/scala/temple/DSL/semantics/TempleBlockTest.scala
Labels: size/M

#212 [go-gen] Add main function generation
  src/e2e/resources/go/user/user.go.snippet
  src/main/scala/temple/generate/server/go/auth/GoAuthServiceGenerator.scala
  src/main/scala/temple/generate/server/go/auth/GoAuthServiceMainGenerator.scala
  src/main/scala/temple/generate/server/go/common/GoCommonGenerator.scala
  src/main/scala/temple/generate/server/go/common/GoCommonMainGenerator.scala
  src/main/scala/temple/generate/server/go/service/GoServiceGenerator.scala
  src/main/scala/temple/generate/server/go/service/main/GoServiceMainGenerator.scala
  src/test/resources/go/complex-user/complexuser.go.snippet
  src/test/resources/go/simple-user/user.go.snippet
  src/test/scala/temple/generate/server/go/testfiles/auth/auth.go.snippet
  src/test/scala/temple/generate/server/go/testfiles/match/match.go.snippet
  src/test/scala/temple/generate/server/go/testfiles/user/user.go.snippet
Labels: size/L

#213 [go-gen][metrics] Populate metric.go
  src/e2e/resources/go/user/metric/metric.go.snippet
  src/main/scala/temple/generate/server/go/common/GoCommonGenerator.scala
  src/main/scala/temple/generate/server/go/service/GoServiceGenerator.scala
  src/main/scala/temple/generate/server/go/service/GoServiceMetricGenerator.scala
  src/main/scala/temple/generate/utils/CodeTerm.scala
  src/main/scala/temple/generate/utils/CodeUtils.scala
  src/test/resources/go/complex-user/metric/metric.go.snippet
  src/test/resources/go/simple-user/metric/metric.go.snippet
  src/test/scala/temple/generate/server/go/testfiles/match/metric/metric.go.snippet
  src/test/scala/temple/generate/server/go/testfiles/user/metric/metric.go.snippet
Labels: size/L

#214 [Go-Map] Auth Server Builder
  src/main/scala/temple/builder/DatabaseBuilder.scala
  src/main/scala/temple/builder/ServerBuilder.scala
  src/main/scala/temple/builder/project/ProjectConfig.scala
  src/test/scala/temple/builder/DatabaseBuilderTest.scala
  src/test/scala/temple/builder/ServerBuilderTest.scala
Labels: size/M

#216 [ast] Remove TargetAuth, it was doing nothing
  src/main/scala/temple/DSL/semantics/Analyzer.scala
  src/main/scala/temple/DSL/semantics/Validator.scala
  src/main/scala/temple/ast/Metadata.scala
Labels: size/XS

#215 [go-gen][hooks] Generate hooks file
  src/e2e/resources/go/user/hook.go.snippet
  src/e2e/scala/temple/SimpleE2ETest.scala
  src/main/scala/temple/generate/server/go/service/GoServiceGenerator.scala
  src/main/scala/temple/generate/server/go/service/GoServiceHookGenerator.scala
  src/test/resources/go/complex-user/hook.go.snippet
  src/test/resources/go/simple-user/hook.go.snippet
  src/test/scala/temple/builder/project/ProjectBuilderTest.scala
  src/test/scala/temple/builder/project/ProjectBuilderTestData.scala
  src/test/scala/temple/generate/server/go/GoServiceGeneratorTestData.scala
  src/test/scala/temple/generate/server/go/testfiles/match/hook.go.snippet
  src/test/scala/temple/generate/server/go/testfiles/user/hook.go.snippet
Labels: size/M

#217 [go-gen][hooks] Add Hook and HookError structs
  src/e2e/resources/go/user/hook.go.snippet
  src/it/scala/temple/containers/GolangSpec.scala
  src/main/scala/temple/generate/server/go/common/GoCommonGenerator.scala
  src/main/scala/temple/generate/server/go/service/GoServiceGenerator.scala
  src/main/scala/temple/generate/server/go/service/GoServiceHookGenerator.scala
  src/test/resources/go/complex-user/hook.go.snippet
  src/test/resources/go/simple-user/hook.go.snippet
  src/test/scala/temple/generate/server/go/testfiles/match/hook.go.snippet
  src/test/scala/temple/generate/server/go/testfiles/user/hook.go.snippet
Labels: size/L

#218 [Go-Map] Update ProjectBuilder to generate Go Auth service
  src/e2e/resources/go/user/user.go.snippet
  src/e2e/scala/temple/SimpleE2ETest.scala
  src/e2e/scala/temple/SimpleE2ETestData.scala
  src/main/scala/temple/ast/Templefile.scala
  src/main/scala/temple/builder/DatabaseBuilder.scala
  src/main/scala/temple/builder/ServerBuilder.scala
  src/main/scala/temple/builder/project/ProjectBuilder.scala
  src/main/scala/temple/builder/project/ProjectConfig.scala
  src/test/resources/go/auth/auth.go.snippet
  src/test/resources/go/auth/comm/handler.go.snippet
  src/test/resources/go/auth/dao/dao.go.snippet
  src/test/resources/go/auth/dao/errors.go.snippet
  src/test/resources/go/auth/go.mod.snippet
  src/test/resources/go/auth/util/util.go.snippet
  src/test/resources/go/complex-user/complexuser.go.snippet
  src/test/resources/go/simple-user/user.go.snippet
  src/test/scala/temple/builder/DatabaseBuilderTest.scala
  src/test/scala/temple/builder/ServerBuilderTest.scala
  src/test/scala/temple/builder/project/ProjectBuilderTest.scala
  src/test/scala/temple/builder/project/ProjectBuilderTestData.scala
Labels: size/XL

#221 [go-gen][hooks] Introduce AddHook methods
  src/e2e/resources/go/user/hook.go.snippet
  src/main/scala/temple/generate/CRUD.scala
  src/main/scala/temple/generate/server/go/service/GoServiceGenerator.scala
  src/main/scala/temple/generate/server/go/service/GoServiceHookGenerator.scala
  src/test/resources/go/complex-user/hook.go.snippet
  src/test/resources/go/simple-user/hook.go.snippet
  src/test/scala/temple/generate/server/go/testfiles/match/hook.go.snippet
  src/test/scala/temple/generate/server/go/testfiles/user/hook.go.snippet
Labels: size/L

#220 [go-gen] Add list handler generation
  src/e2e/resources/go/user/user.go.snippet
  src/main/scala/temple/generate/server/go/common/GoCommonGenerator.scala
  src/main/scala/temple/generate/server/go/service/GoServiceGenerator.scala
  src/main/scala/temple/generate/server/go/service/main/GoServiceMainCreateHandlerGenerator.scala
  src/main/scala/temple/generate/server/go/service/main/GoServiceMainDeleteHandlerGenerator.scala
  src/main/scala/temple/generate/server/go/service/main/GoServiceMainGenerator.scala
  src/main/scala/temple/generate/server/go/service/main/GoServiceMainHandlersGenerator.scala
  src/main/scala/temple/generate/server/go/service/main/GoServiceMainListHandlerGenerator.scala
  src/main/scala/temple/generate/server/go/service/main/GoServiceMainReadHandlerGenerator.scala
  src/main/scala/temple/generate/server/go/service/main/GoServiceMainUpdateHandlerGenerator.scala
  src/main/scala/temple/generate/utils/CodeTerm.scala
  src/test/resources/go/complex-user/complexuser.go.snippet
  src/test/resources/go/simple-user/user.go.snippet
  src/test/scala/temple/generate/server/go/testfiles/match/match.go.snippet
  src/test/scala/temple/generate/server/go/testfiles/user/user.go.snippet
Labels: size/L

#219 [Codegen] Make CodeTermClass a typeclass, to allow for arbitrary nesting
  src/main/scala/temple/generate/server/go/common/GoCommonGenerator.scala
  src/main/scala/temple/generate/utils/CodeTerm.scala
Labels: size/M

#224 [docker] Add trailing slash to path
  src/e2e/scala/temple/SimpleE2ETestData.scala
  src/main/scala/temple/builder/DockerfileBuilder.scala
  src/test/scala/temple/builder/DockerfileBuilderTestData.scala
  src/test/scala/temple/builder/project/ProjectBuilderTestData.scala
Labels: size/S

#223 [go-gen][metrics] Extract shared logic to common generator
  src/main/scala/temple/generate/server/go/common/GoCommonMetricGenerator.scala
  src/main/scala/temple/generate/server/go/service/GoServiceGenerator.scala
  src/main/scala/temple/generate/server/go/service/GoServiceMetricGenerator.scala
Labels: size/L

#225 Auth metric gen
  src/main/scala/temple/generate/server/go/auth/GoAuthServiceGenerator.scala
  src/main/scala/temple/generate/server/go/auth/GoAuthServiceMetricGenerator.scala
  src/main/scala/temple/generate/server/go/common/GoCommonMetricGenerator.scala
  src/main/scala/temple/generate/server/go/service/GoServiceGenerator.scala
  src/main/scala/temple/generate/server/go/service/GoServiceMetricGenerator.scala
  src/test/resources/go/auth/metric/metric.go.snippet
  src/test/scala/temple/builder/project/ProjectBuilderTest.scala
  src/test/scala/temple/builder/project/ProjectBuilderTestData.scala
  src/test/scala/temple/generate/server/go/GoAuthServiceGeneratorTestData.scala
  src/test/scala/temple/generate/server/go/testfiles/auth/metric/metric.go.snippet
Labels: size/M

#228 [go-gen] Fix foreign keys being passed in as UUID type
  src/it/scala/temple/generate/server/GoGeneratorIntegrationTestData.scala
  src/main/scala/temple/builder/ServerBuilder.scala
  src/main/scala/temple/generate/server/go/common/GoCommonGenerator.scala
  src/test/scala/temple/generate/server/go/GoServiceGeneratorTestData.scala
Labels: size/S

#227 [go-gen][hook] Move common hook logic into shared package
  src/main/scala/temple/generate/server/go/auth/GoAuthServiceGenerator.scala
  src/main/scala/temple/generate/server/go/common/GoCommonHookGenerator.scala
  src/main/scala/temple/generate/server/go/service/GoServiceGenerator.scala
  src/main/scala/temple/generate/server/go/service/GoServiceHookGenerator.scala
  src/test/resources/go/auth/hook.go.snippet
  src/test/scala/temple/builder/project/ProjectBuilderTest.scala
  src/test/scala/temple/builder/project/ProjectBuilderTestData.scala
  src/test/scala/temple/generate/server/go/GoAuthServiceGeneratorTestData.scala
  src/test/scala/temple/generate/server/go/testfiles/auth/hook.go.snippet
Labels: size/M

#226 [Go-Map] Update E2E tests to check for generated auth go files
  src/e2e/resources/go/auth/auth.go.snippet
  src/e2e/resources/go/auth/comm/handler.go.snippet
  src/e2e/resources/go/auth/dao/dao.go.snippet
  src/e2e/resources/go/auth/dao/errors.go.snippet
  src/e2e/resources/go/auth/go.mod.snippet
  src/e2e/resources/go/auth/hook.go.snippet
  src/e2e/resources/go/auth/metric/metric.go.snippet
  src/e2e/resources/go/auth/util/util.go.snippet
  src/e2e/scala/temple/SimpleE2ETest.scala
  src/e2e/scala/temple/SimpleE2ETestData.scala
Labels: size/XL

#229 [config] Add config JSON generator
  src/main/scala/temple/generate/server/config/ServerConfigGenerator.scala
  src/main/scala/temple/generate/server/config/ast/DatabaseConfig.scala
  src/main/scala/temple/generate/server/config/ast/ServerConfig.scala
  src/test/scala/temple/generate/server/config/ServerConfigGeneratorTest.scala
  src/test/scala/temple/generate/server/config/ServerConfigGeneratorTestData.scala
Labels: size/M

#232 [go-gen] Add generation of create handler
  src/e2e/resources/go/user/user.go.snippet
  src/main/scala/temple/generate/server/ServiceRoot.scala
  src/main/scala/temple/generate/server/go/GoHTTPStatus.scala
  src/main/scala/temple/generate/server/go/service/GoServiceGenerator.scala
  src/main/scala/temple/generate/server/go/service/main/GoServiceMainCreateHandlerGenerator.scala
  src/main/scala/temple/generate/server/go/service/main/GoServiceMainGenerator.scala
  src/main/scala/temple/generate/server/go/service/main/GoServiceMainHandlersGenerator.scala
  src/main/scala/temple/generate/server/go/service/main/GoServiceMainListHandlerGenerator.scala
  src/test/resources/go/complex-user/complexuser.go.snippet
  src/test/resources/go/simple-user/user.go.snippet
  src/test/scala/temple/generate/server/go/testfiles/match/match.go.snippet
  src/test/scala/temple/generate/server/go/testfiles/user/user.go.snippet
Labels: size/XL

#231 [go-gen][auth][hook] Generate hooks for auth service
  src/e2e/resources/go/auth/hook.go.snippet
  src/main/scala/temple/generate/server/go/auth/GoAuthServiceGenerator.scala
  src/main/scala/temple/generate/server/go/auth/GoAuthServiceHookGenerator.scala
  src/main/scala/temple/generate/server/go/common/GoCommonHookGenerator.scala
  src/main/scala/temple/generate/server/go/service/GoServiceHookGenerator.scala
  src/test/resources/go/auth/hook.go.snippet
  src/test/scala/temple/generate/server/go/testfiles/auth/hook.go.snippet
Labels: size/L

#234 [Auth-Map] Add GeneratedBlock trait for more abstraction
  src/main/scala/temple/DSL/semantics/Validator.scala
  src/main/scala/temple/ast/AuthServiceBlock.scala
  src/main/scala/temple/ast/GeneratedBlock.scala
  src/main/scala/temple/ast/ServiceBlock.scala
  src/main/scala/temple/ast/Templefile.scala
  src/main/scala/temple/builder/DatabaseBuilder.scala
  src/main/scala/temple/builder/DockerfileBuilder.scala
  src/main/scala/temple/builder/OrchestrationBuilder.scala
  src/main/scala/temple/builder/ServerBuilder.scala
  src/main/scala/temple/builder/project/ProjectBuilder.scala
  src/main/scala/temple/test/ProjectTester.scala
  src/test/scala/temple/builder/ServerBuilderTest.scala
Labels: size/L

#222 [Go-gen] Update casing in all the generation code
  src/e2e/resources/go/user/dao/dao.go.snippet
  src/e2e/resources/go/user/dao/errors.go.snippet
  src/e2e/resources/go/user/go.mod.snippet
  src/e2e/resources/go/user/hook.go.snippet
  src/e2e/resources/go/user/user.go.snippet
  src/e2e/resources/grafana/simple-temple-user.json
  src/e2e/scala/temple/SimpleE2ETest.scala
  src/e2e/scala/temple/SimpleE2ETestData.scala
  src/it/scala/temple/generate/server/GoGeneratorIntegrationTestData.scala
  src/main/scala/temple/builder/ServerBuilder.scala
  src/main/scala/temple/builder/project/ProjectBuilder.scala
  src/main/scala/temple/generate/FileSystem.scala
  src/main/scala/temple/generate/server/ServiceRoot.scala
  src/main/scala/temple/generate/server/go/auth/GoAuthServiceGenerator.scala
  src/main/scala/temple/generate/server/go/common/GoCommonGenerator.scala
  src/main/scala/temple/generate/server/go/common/GoCommonMainGenerator.scala
  src/main/scala/temple/generate/server/go/service/GoServiceGenerator.scala
  src/main/scala/temple/generate/server/go/service/GoServiceHookGenerator.scala
  src/main/scala/temple/generate/server/go/service/dao/GoServiceDAOFunctionsGenerator.scala
  src/main/scala/temple/generate/server/go/service/dao/GoServiceDAOGenerator.scala
  src/main/scala/temple/generate/server/go/service/dao/GoServiceDAOInputStructsGenerator.scala
  src/main/scala/temple/generate/server/go/service/dao/GoServiceDAOInterfaceGenerator.scala
  src/main/scala/temple/generate/server/go/service/main/GoServiceMainCreateHandlerGenerator.scala
  src/main/scala/temple/generate/server/go/service/main/GoServiceMainGenerator.scala
  src/main/scala/temple/generate/server/go/service/main/GoServiceMainHandlersGenerator.scala
  src/main/scala/temple/generate/server/go/service/main/GoServiceMainListHandlerGenerator.scala
  src/main/scala/temple/generate/server/go/service/main/GoServiceMainStructGenerator.scala
  src/main/scala/temple/generate/target/openapi/OpenAPIGenerator.scala
  src/test/resources/go/complex-user/complex-user.go.snippet
  src/test/resources/go/complex-user/dao/dao.go.snippet
  src/test/resources/go/complex-user/dao/errors.go.snippet
  src/test/resources/go/complex-user/go.mod.snippet
  src/test/resources/go/complex-user/hook.go.snippet
  src/test/resources/go/simple-user/dao/dao.go.snippet
  src/test/resources/go/simple-user/dao/errors.go.snippet
  src/test/resources/go/simple-user/go.mod.snippet
  src/test/resources/go/simple-user/hook.go.snippet
  src/test/resources/go/simple-user/simple-user.go.snippet
  src/test/resources/grafana/complex-user.json
  src/test/resources/grafana/temple-user.json
  src/test/scala/temple/DSL/parser/DSLParserMatchers.scala
  src/test/scala/temple/builder/BuilderTestData.scala
  src/test/scala/temple/builder/ServerBuilderTest.scala
  src/test/scala/temple/builder/project/ProjectBuilderTest.scala
  src/test/scala/temple/builder/project/ProjectBuilderTestData.scala
  src/test/scala/temple/generate/FileMatchers.scala
  src/test/scala/temple/generate/server/go/GoServiceGeneratorTest.scala
  src/test/scala/temple/generate/server/go/GoServiceGeneratorTestData.scala
Labels: size/XXL

#237 [go-gen] Replace createdByAttribute with optional
  src/it/scala/temple/generate/server/GoGeneratorIntegrationTestData.scala
  src/main/scala/temple/builder/DatabaseBuilder.scala
  src/main/scala/temple/builder/ServerBuilder.scala
  src/main/scala/temple/generate/server/CreatedByAttribute.scala
  src/main/scala/temple/generate/server/ServiceRoot.scala
  src/main/scala/temple/generate/server/go/service/GoServiceGenerator.scala
  src/main/scala/temple/generate/server/go/service/dao/GoServiceDAOFunctionsGenerator.scala
  src/main/scala/temple/generate/server/go/service/dao/GoServiceDAOGenerator.scala
  src/main/scala/temple/generate/server/go/service/dao/GoServiceDAOInputStructsGenerator.scala
  src/main/scala/temple/generate/server/go/service/dao/GoServiceDAOInterfaceGenerator.scala
  src/main/scala/temple/generate/server/go/service/main/GoServiceMainHandlersGenerator.scala
  src/main/scala/temple/generate/server/go/service/main/GoServiceMainListHandlerGenerator.scala
  src/test/scala/temple/builder/DatabaseBuilderTest.scala
  src/test/scala/temple/builder/ServerBuilderTest.scala
  src/test/scala/temple/generate/server/go/GoServiceGeneratorTestData.scala
Labels: size/L

#236 [Validator] Perform renaming of structs/services and attributes (without test update)
  src/main/scala/temple/DSL/semantics/NameClashes.scala
  src/main/scala/temple/DSL/semantics/SemanticContext.scala
  src/main/scala/temple/DSL/semantics/ServiceRenamer.scala
  src/main/scala/temple/DSL/semantics/Validator.scala
Labels: size/L

#235 [Validator] Perform renaming of structs/services and attributes (just the tests)
  src/e2e/resources/go/user/dao/dao.go.snippet
  src/e2e/resources/go/user/dao/errors.go.snippet
  src/e2e/resources/go/user/go.mod.snippet
  src/e2e/resources/go/user/hook.go.snippet
  src/e2e/resources/go/user/metric/metric.go.snippet
  src/e2e/resources/go/user/user.go.snippet
  src/e2e/resources/grafana/simple-temple-user.json
  src/e2e/scala/temple/DSL/ParserE2ETest.scala
  src/e2e/scala/temple/SimpleE2ETest.scala
  src/e2e/scala/temple/SimpleE2ETestData.scala
  src/test/scala/temple/DSL/parser/DSLParserTest.scala
  src/test/scala/temple/testfiles/simple.temple
Labels: size/XL

#230 [Auth-Map] Update projectBuilder targets to generate auth services
  src/e2e/resources/go/user/user.go.snippet
  src/e2e/scala/temple/DSL/ParserE2ETest.scala
  src/e2e/scala/temple/SimpleE2ETest.scala
  src/e2e/scala/temple/SimpleE2ETestData.scala
  src/it/scala/temple/generate/docker/DockerGeneratorIntegrationTestData.scala
  src/main/scala/temple/DSL/semantics/Analyzer.scala
  src/main/scala/temple/DSL/semantics/ServiceRenamer.scala
  src/main/scala/temple/DSL/semantics/Validator.scala
  src/main/scala/temple/ast/AbstractServiceBlock.scala
  src/main/scala/temple/ast/ServiceBlock.scala
  src/main/scala/temple/ast/Templefile.scala
  src/main/scala/temple/builder/DatabaseBuilder.scala
  src/main/scala/temple/builder/DockerfileBuilder.scala
  src/main/scala/temple/builder/OpenAPIBuilder.scala
  src/main/scala/temple/builder/OrchestrationBuilder.scala
  src/main/scala/temple/builder/ServerBuilder.scala
  src/main/scala/temple/builder/project/ProjectBuilder.scala
  src/main/scala/temple/builder/project/ProjectConfig.scala
  src/main/scala/temple/generate/server/go/common/GoCommonGenerator.scala
  src/main/scala/temple/generate/server/go/common/GoCommonMainGenerator.scala
  src/main/scala/temple/generate/server/go/service/GoServiceHookGenerator.scala
  src/main/scala/temple/generate/server/go/service/dao/GoServiceDAOFunctionsGenerator.scala
  src/main/scala/temple/generate/server/go/service/dao/GoServiceDAOGenerator.scala
  src/main/scala/temple/generate/server/go/service/dao/GoServiceDAOInputStructsGenerator.scala
  src/main/scala/temple/generate/server/go/service/dao/GoServiceDAOInterfaceGenerator.scala
  src/main/scala/temple/generate/server/go/service/main/GoServiceMainCreateHandlerGenerator.scala
  src/main/scala/temple/generate/server/go/service/main/GoServiceMainListHandlerGenerator.scala
  src/main/scala/temple/generate/target/openapi/OpenAPIGenerator.scala
  src/main/scala/temple/test/ProjectTester.scala
  src/main/scala/temple/test/internal/CRUDServiceTest.scala
  src/main/scala/temple/test/internal/ServiceTestUtils.scala
  src/test/resources/go/complex-user/complex-user.go.snippet
  src/test/resources/go/simple-user/simple-user.go.snippet
  src/test/resources/grafana/auth.json
  src/test/resources/kube/auth/auth-db-deployment.yaml
  src/test/resources/kube/auth/auth-db-service.yaml
  src/test/resources/kube/auth/auth-db-storage.yaml
  src/test/resources/kube/auth/auth-deployment.yaml
  src/test/resources/kube/auth/auth-service.yaml
  src/test/scala/temple/DSL/semantics/SemanticAnalyzerTest.scala
  src/test/scala/temple/DSL/semantics/TempleBlockTest.scala
  src/test/scala/temple/DSL/semantics/ValidatorTest.scala
  src/test/scala/temple/builder/BuilderTestData.scala
  src/test/scala/temple/builder/ServerBuilderTest.scala
  src/test/scala/temple/builder/project/ProjectBuilderTest.scala
  src/test/scala/temple/builder/project/ProjectBuilderTestData.scala
  src/test/scala/temple/detail/LanguageSpecificDetailBuilderTestData.scala
  src/test/scala/temple/generate/server/go/GoServiceGeneratorTestData.scala
Labels: size/XXL

#241 [newline] Add newlines consistently to all generated files
  src/e2e/resources/simple-temple-expected/auth-db/init.sql
  src/e2e/resources/simple-temple-expected/booking-db/init.sql
  src/e2e/resources/simple-temple-expected/grafana/provisioning/dashboards/auth.json
  src/e2e/resources/simple-temple-expected/grafana/provisioning/dashboards/booking.json
  src/e2e/resources/simple-temple-expected/grafana/provisioning/dashboards/simple-temple-test-group.json
  src/e2e/resources/simple-temple-expected/grafana/provisioning/dashboards/simple-temple-test-user.json
  src/e2e/resources/simple-temple-expected/kong/configure-kong.sh
  src/e2e/resources/simple-temple-expected/simple-temple-test-group-db/init.sql
  src/e2e/resources/simple-temple-expected/simple-temple-test-user-db/init.sql
  src/e2e/scala/temple/SimpleE2ETest.scala
  src/main/scala/temple/builder/project/ProjectBuilder.scala
  src/main/scala/temple/generate/kube/KongConfigGenerator.scala
  src/main/scala/temple/generate/metrics/grafana/GrafanaDashboardGenerator.scala
  src/test/resources/grafana/auth.json
  src/test/resources/grafana/complex-user.json
  src/test/resources/grafana/temple-user.json
  src/test/resources/kong/configure-kong.sh
  src/test/scala/temple/builder/project/ProjectBuilderTest.scala
  src/test/scala/temple/builder/project/ProjectBuilderTestData.scala
  src/test/scala/temple/generate/FileMatchers.scala
  src/test/scala/temple/generate/metrics/grafana/GrafanaDashboardGeneratorTestUtils.scala
Labels: size/M

#243 [go-gen] Fix create handler to handle auth/project-auth
  src/it/scala/temple/generate/server/GoGeneratorIntegrationTestData.scala
  src/main/scala/temple/builder/ServerBuilder.scala
  src/main/scala/temple/generate/server/ServiceRoot.scala
  src/main/scala/temple/generate/server/go/service/GoServiceCommGenerator.scala
  src/main/scala/temple/generate/server/go/service/GoServiceGenerator.scala
  src/main/scala/temple/generate/server/go/service/main/GoServiceMainCreateHandlerGenerator.scala
  src/main/scala/temple/generate/server/go/service/main/GoServiceMainHandlersGenerator.scala
  src/test/resources/go/simple-user/simple-user.go.snippet
  src/test/scala/temple/builder/ServerBuilderTest.scala
  src/test/scala/temple/generate/server/go/GoServiceGeneratorTestData.scala
Labels: size/M

#242 [builder] Refactor project builder into distinct functions for each component
  src/main/scala/temple/builder/project/ProjectBuilder.scala
  src/main/scala/temple/builder/project/ProjectConfig.scala
Labels: size/L

#240 [Validator] Treat service blocks as struct blocks for ease of traversal
  src/it/scala/temple/generate/docker/DockerGeneratorIntegrationTestData.scala
  src/main/scala/temple/DSL/semantics/ServiceRenamer.scala
  src/main/scala/temple/DSL/semantics/Validator.scala
  src/main/scala/temple/ast/AbstractServiceBlock.scala
  src/main/scala/temple/ast/AttributeBlock.scala
  src/main/scala/temple/ast/Metadata.scala
  src/main/scala/temple/ast/StructBlock.scala
  src/main/scala/temple/builder/DatabaseBuilder.scala
  src/main/scala/temple/builder/project/ProjectBuilder.scala
Labels: size/L

#244 [Validators] Add naming validators for Go, including functional validators
  src/main/scala/temple/DSL/semantics/NameClashes.scala
  src/main/scala/temple/DSL/semantics/Validator.scala
  src/test/scala/temple/DSL/semantics/NameClashesTest.scala
Labels: size/L

#245 [go-gen] Add read handler generation
  src/e2e/resources/simple-temple-expected/booking/booking.go
  src/e2e/resources/simple-temple-expected/simple-temple-test-group/simple-temple-test-group.go
  src/e2e/resources/simple-temple-expected/simple-temple-test-user/simple-temple-test-user.go
  src/main/scala/temple/generate/server/go/GoHTTPStatus.scala
  src/main/scala/temple/generate/server/go/common/GoCommonGenerator.scala
  src/main/scala/temple/generate/server/go/service/GoServiceCommGenerator.scala
  src/main/scala/temple/generate/server/go/service/GoServiceGenerator.scala
  src/main/scala/temple/generate/server/go/service/dao/GoServiceDAOFunctionsGenerator.scala
  src/main/scala/temple/generate/server/go/service/main/GoServiceMainCreateHandlerGenerator.scala
  src/main/scala/temple/generate/server/go/service/main/GoServiceMainGenerator.scala
  src/main/scala/temple/generate/server/go/service/main/GoServiceMainHandlersGenerator.scala
  src/main/scala/temple/generate/server/go/service/main/GoServiceMainListHandlerGenerator.scala
  src/main/scala/temple/generate/server/go/service/main/GoServiceMainReadHandlerGenerator.scala
  src/test/resources/project-builder-complex/complex-user/complex-user.go
  src/test/resources/project-builder-simple/temple-user/temple-user.go
  src/test/scala/temple/generate/server/go/testfiles/match/match.go.snippet
  src/test/scala/temple/generate/server/go/testfiles/user/user.go.snippet
Labels: size/XL

#247 [Mapping] Implicit IDAttribute
  src/e2e/resources/simple-temple-expected/api/simple-temple-test.openapi.yaml
  src/e2e/resources/simple-temple-expected/auth-db/init.sql
  src/e2e/resources/simple-temple-expected/booking-db/init.sql
  src/e2e/resources/simple-temple-expected/booking/dao/dao.go
  src/e2e/resources/simple-temple-expected/simple-temple-test-group-db/init.sql
  src/e2e/resources/simple-temple-expected/simple-temple-test-group/dao/dao.go
  src/e2e/resources/simple-temple-expected/simple-temple-test-user-db/init.sql
  src/e2e/resources/simple-temple-expected/simple-temple-test-user/dao/dao.go
  src/e2e/scala/temple/DSL/ParserE2ETest.scala
  src/main/scala/temple/DSL/semantics/Validator.scala
  src/main/scala/temple/ast/AbstractServiceBlock.scala
  src/main/scala/temple/ast/Attribute.scala
  src/main/scala/temple/builder/DatabaseBuilder.scala
  src/main/scala/temple/builder/ServerBuilder.scala
  src/test/resources/project-builder-complex/api/sample-complex-project.openapi.yaml
  src/test/resources/project-builder-complex/auth-db/init.sql
  src/test/resources/project-builder-complex/complex-user-db/init.sql
  src/test/resources/project-builder-complex/complex-user/dao/dao.go
  src/test/resources/project-builder-simple/api/sample-project.openapi.yaml
  src/test/resources/project-builder-simple/temple-user-db/init.sql
  src/test/resources/project-builder-simple/temple-user/dao/dao.go
  src/test/scala/temple/builder/project/ProjectBuilderTestData.scala
Labels: size/L

#251 [go-gen] Add delete handler generation
  src/e2e/resources/simple-temple-expected/booking/booking.go
  src/e2e/resources/simple-temple-expected/simple-temple-test-group/simple-temple-test-group.go
  src/main/scala/temple/generate/server/go/service/GoServiceGenerator.scala
  src/main/scala/temple/generate/server/go/service/main/GoServiceMainDeleteHandlerGenerator.scala
  src/main/scala/temple/generate/server/go/service/main/GoServiceMainHandlersGenerator.scala
  src/main/scala/temple/generate/server/go/service/main/GoServiceMainReadHandlerGenerator.scala
  src/test/resources/project-builder-complex/complex-user/complex-user.go
  src/test/resources/project-builder-simple/temple-user/temple-user.go
  src/test/scala/temple/generate/server/go/testfiles/match/match.go.snippet
  src/test/scala/temple/generate/server/go/testfiles/user/user.go.snippet
Labels: size/L

#249 [grafana] Add support for structs in Grafana
  src/e2e/resources/simple-temple-expected/grafana/provisioning/dashboards/simple-temple-test-user.json
  src/main/scala/temple/builder/MetricsBuilder.scala
  src/main/scala/temple/builder/project/ProjectBuilder.scala
  src/test/resources/project-builder-complex/grafana/provisioning/dashboards/complex-user.json
Labels: size/XXL

#252 [dsl] Support #metrics in Templefile
  src/e2e/scala/temple/DSL/ParserE2ETest.scala
  src/main/scala/temple/DSL/semantics/Analyzer.scala
  src/main/scala/temple/DSL/semantics/ServiceRenamer.scala
  src/main/scala/temple/DSL/semantics/Validator.scala
  src/main/scala/temple/ast/Metadata.scala
  src/test/scala/temple/DSL/parser/DSLParserTest.scala
  src/test/scala/temple/DSL/semantics/ValidatorTest.scala
  src/test/scala/temple/testfiles/simple.temple
Labels: size/S

#253 [go-gen] Add update handler generation
  src/e2e/resources/simple-temple-expected/booking/booking.go
  src/e2e/resources/simple-temple-expected/simple-temple-test-group/simple-temple-test-group.go
  src/e2e/resources/simple-temple-expected/simple-temple-test-user/simple-temple-test-user.go
  src/main/scala/temple/generate/server/go/service/main/GoServiceMainCreateHandlerGenerator.scala
  src/main/scala/temple/generate/server/go/service/main/GoServiceMainHandlersGenerator.scala
  src/main/scala/temple/generate/server/go/service/main/GoServiceMainReadHandlerGenerator.scala
  src/main/scala/temple/generate/server/go/service/main/GoServiceMainUpdateHandlerGenerator.scala
  src/test/resources/project-builder-complex/complex-user/complex-user.go
  src/test/resources/project-builder-simple/temple-user/temple-user.go
  src/test/scala/temple/generate/server/go/testfiles/match/match.go.snippet
  src/test/scala/temple/generate/server/go/testfiles/user/user.go.snippet
Labels: size/XL

#248 [Parser] Remove underscores from Templefile variable names
  src/e2e/scala/temple/DSL/ParserE2ETest.scala
  src/main/scala/temple/DSL/parser/DSLParser.scala
  src/test/scala/temple/DSL/parser/DSLParserMatchers.scala
  src/test/scala/temple/DSL/parser/DSLParserTest.scala
Labels: size/M

#250 [Validator] Validate readable/writable by this has an auth block
  src/main/scala/temple/DSL/semantics/Validator.scala
  src/test/scala/temple/DSL/semantics/ValidatorTest.scala
Labels: size/M

#254 [config] Map into config.json
  src/e2e/resources/simple-temple-expected/booking/config.json
  src/e2e/resources/simple-temple-expected/simple-temple-test-group/config.json
  src/e2e/resources/simple-temple-expected/simple-temple-test-user/config.json
  src/main/scala/temple/builder/ServerBuilder.scala
  src/main/scala/temple/builder/project/ProjectBuilder.scala
  src/main/scala/temple/generate/server/config/ServerConfigGenerator.scala
  src/test/resources/project-builder-complex/complex-user/config.json
  src/test/resources/project-builder-simple/temple-user/config.json
  src/test/scala/temple/builder/project/ProjectBuilderTest.scala
  src/test/scala/temple/builder/project/ProjectBuilderTestData.scala
  src/test/scala/temple/generate/server/config/ServerConfigGeneratorTestData.scala
Labels: size/L

#255 [go-gen] Fix handling of @serverSet attributes in DAO generation
  src/it/scala/temple/generate/server/GoGeneratorIntegrationTestData.scala
  src/main/scala/temple/generate/server/go/service/GoServiceGenerator.scala
  src/main/scala/temple/generate/server/go/service/dao/GoServiceDAOFunctionsGenerator.scala
  src/main/scala/temple/generate/server/go/service/dao/GoServiceDAOInputStructsGenerator.scala
  src/main/scala/temple/generate/server/go/service/main/GoServiceMainCreateHandlerGenerator.scala
  src/main/scala/temple/generate/server/go/service/main/GoServiceMainUpdateHandlerGenerator.scala
  src/test/scala/temple/generate/server/go/GoServiceGeneratorTestData.scala
  src/test/scala/temple/generate/server/go/testfiles/match/dao/dao.go.snippet
Labels: size/M

#256 [Kube-Gen] Deploy.sh
  src/e2e/resources/simple-temple-expected/deploy.sh
  src/it/scala/temple/generate/kube/KubernetesGeneratorIntegrationTestData.scala
  src/main/resources/shell/deploy.sh.body.snippet
  src/main/resources/shell/deploy.sh.header.snippet
  src/main/resources/shell/deploy.sh.metrics.snippet
  src/main/scala/temple/builder/OrchestrationBuilder.scala
  src/main/scala/temple/generate/kube/DeployScriptGenerator.scala
  src/main/scala/temple/generate/kube/KubernetesGenerator.scala
  src/main/scala/temple/generate/kube/ast/OrchestrationType.scala
  src/test/resources/project-builder-complex/deploy.sh
  src/test/resources/project-builder-simple/deploy.sh
  src/test/resources/shell/deploy-without-metrics.sh
  src/test/resources/shell/deploy.sh
  src/test/scala/temple/TestUtils.scala
  src/test/scala/temple/builder/project/ProjectBuilderTestData.scala
  src/test/scala/temple/generate/kube/KongConfigGeneratorTest.scala
  src/test/scala/temple/generate/kube/KubernetesGeneratorTest.scala
  src/test/scala/temple/generate/kube/UnitTestData.scala
Labels: size/XS

#257 [metrics] Only generate metrics if explicitly requested
  src/main/scala/temple/builder/project/ProjectBuilder.scala
  src/test/resources/project-builder-simple/grafana/provisioning/dashboards/dashboards.yml
  src/test/resources/project-builder-simple/grafana/provisioning/dashboards/temple-user.json
  src/test/resources/project-builder-simple/grafana/provisioning/datasources/datasource.yml
  src/test/resources/project-builder-simple/prometheus/prometheus.yml
  src/test/scala/temple/builder/project/ProjectBuilderTestData.scala
Labels: size/XL

#258 [config] Add config.json for auth services
  src/e2e/resources/simple-temple-expected/auth/config.json
  src/main/scala/temple/builder/project/ProjectBuilder.scala
  src/test/resources/project-builder-complex/auth/config.json
Labels: size/M

#260 [it] Add integration test against simple.temple
  docker/deploy.sh
  docker/shell2http.Dockerfile
  src/e2e/resources/simple-temple-expected/booking/booking.go
  src/e2e/resources/simple-temple-expected/simple-temple-test-group/simple-temple-test-group.go
  src/e2e/resources/simple-temple-expected/simple-temple-test-user/simple-temple-test-user.go
  src/it/scala/temple/containers/DockerShell2HttpService.scala
  src/it/scala/temple/generate/server/GoGeneratorIntegrationTest.scala
  src/main/scala/temple/generate/server/go/service/GoServiceGenerator.scala
  src/main/scala/temple/generate/server/go/service/main/GoServiceMainCreateHandlerGenerator.scala
  src/main/scala/temple/generate/server/go/service/main/GoServiceMainHandlersGenerator.scala
  src/main/scala/temple/generate/server/go/service/main/GoServiceMainUpdateHandlerGenerator.scala
  src/test/resources/project-builder-complex/complex-user/complex-user.go
  src/test/resources/project-builder-simple/temple-user/temple-user.go
Labels: size/M

#259 [deploy] Add push-image.sh script to push images to a local registry
  src/e2e/resources/simple-temple-expected/push-image.sh
  src/it/scala/temple/generate/kube/KubernetesGeneratorIntegrationTest.scala
  src/main/scala/temple/builder/project/ProjectBuilder.scala
  src/main/scala/temple/generate/kube/KubernetesGenerator.scala
  src/main/scala/temple/generate/kube/PushImageScriptGenerator.scala
  src/test/resources/project-builder-complex/push-image.sh
  src/test/resources/project-builder-simple/push-image.sh
  src/test/scala/temple/generate/kube/KubernetesGeneratorTest.scala
Labels: size/M

#261 [hooks] Remove arguments if service has no attributes
  docker/deploy.sh
  docker/shell2http.Dockerfile
  src/e2e/resources/simple-temple-expected/booking/hook.go
  src/e2e/resources/simple-temple-expected/simple-temple-test-group/hook.go
  src/e2e/resources/simple-temple-expected/simple-temple-test-user/hook.go
  src/it/scala/temple/containers/DockerShell2HttpService.scala
  src/main/scala/temple/generate/server/go/service/GoServiceGenerator.scala
  src/main/scala/temple/generate/server/go/service/GoServiceHookGenerator.scala
Labels: size/M

#262 [docker-gen] Remove go.sum from Dockerfile
  src/e2e/resources/simple-temple-expected/auth/Dockerfile
  src/e2e/resources/simple-temple-expected/booking/Dockerfile
  src/e2e/resources/simple-temple-expected/simple-temple-test-group/Dockerfile
  src/e2e/resources/simple-temple-expected/simple-temple-test-user/Dockerfile
  src/main/scala/temple/builder/DockerfileBuilder.scala
  src/test/resources/project-builder-complex/auth/Dockerfile
  src/test/resources/project-builder-complex/complex-user/Dockerfile
  src/test/resources/project-builder-simple/temple-user/Dockerfile
  src/test/scala/temple/builder/DockerfileBuilderTestData.scala
Labels: size/S

#263 [local-registry] Add deployment yaml files for local registry service
  src/e2e/resources/simple-temple-expected/kube/deploy/deploy-daemon-set.yaml
  src/e2e/resources/simple-temple-expected/kube/deploy/deploy-replication-controller.yaml
  src/e2e/resources/simple-temple-expected/kube/deploy/deploy-service.yaml
  src/main/resources/kube/deploy/deploy-daemon-set.yaml
  src/main/resources/kube/deploy/deploy-replication-controller.yaml
  src/main/resources/kube/deploy/deploy-service.yaml
  src/main/scala/temple/generate/kube/KubernetesGenerator.scala
  src/test/resources/project-builder-complex/kube/deploy/deploy-daemon-set.yaml
  src/test/resources/project-builder-complex/kube/deploy/deploy-replication-controller.yaml
  src/test/resources/project-builder-complex/kube/deploy/deploy-service.yaml
  src/test/resources/project-builder-simple/kube/deploy/deploy-daemon-set.yaml
  src/test/resources/project-builder-simple/kube/deploy/deploy-replication-controller.yaml
  src/test/resources/project-builder-simple/kube/deploy/deploy-service.yaml
Labels: size/L

#265 [go-gen] Fix declare case and blob type encoding
  src/main/scala/temple/generate/server/go/service/GoServiceGenerator.scala
  src/main/scala/temple/generate/server/go/service/main/GoServiceMainCreateHandlerGenerator.scala
  src/main/scala/temple/generate/server/go/service/main/GoServiceMainGenerator.scala
  src/main/scala/temple/generate/server/go/service/main/GoServiceMainHandlersGenerator.scala
  src/main/scala/temple/generate/server/go/service/main/GoServiceMainUpdateHandlerGenerator.scala
  src/test/resources/project-builder-complex/complex-user/complex-user.go
  src/test/resources/project-builder-simple/temple-user/temple-user.go
Labels: size/M

#264 [deploy] Deploy registry service
  src/e2e/resources/simple-temple-expected/deploy.sh
  src/e2e/resources/simple-temple-expected/kube/auth/deployment.yaml
  src/e2e/resources/simple-temple-expected/kube/booking/deployment.yaml
  src/e2e/resources/simple-temple-expected/kube/simple-temple-test-group/deployment.yaml
  src/e2e/resources/simple-temple-expected/kube/simple-temple-test-user/deployment.yaml
  src/main/resources/shell/deploy.sh.body.snippet
  src/main/resources/shell/deploy.sh.deployment.snippet
  src/main/scala/temple/builder/OrchestrationBuilder.scala
  src/main/scala/temple/builder/project/ProjectConfig.scala
  src/main/scala/temple/generate/kube/DeployScriptGenerator.scala
  src/test/resources/kube/user-deployment.yaml
  src/test/resources/project-builder-complex/deploy.sh
  src/test/resources/project-builder-complex/kube/auth/deployment.yaml
  src/test/resources/project-builder-complex/kube/complex-user/deployment.yaml
  src/test/resources/project-builder-simple/deploy.sh
  src/test/resources/project-builder-simple/kube/temple-user/deployment.yaml
  src/test/resources/shell/deploy-without-metrics.sh
  src/test/resources/shell/deploy.sh
  src/test/scala/temple/generate/kube/UnitTestData.scala
Labels: size/L

#266 [CreatedBy] Add implicit CreatedBy Attribute where required
  src/e2e/resources/simple-temple-expected/api/simple-temple-test.openapi.yaml
  src/e2e/resources/simple-temple-expected/booking-db/init.sql
  src/e2e/resources/simple-temple-expected/booking/dao/dao.go
  src/e2e/resources/simple-temple-expected/simple-temple-test-group-db/init.sql
  src/e2e/resources/simple-temple-expected/simple-temple-test-group/dao/dao.go
  src/e2e/resources/simple-temple-expected/simple-temple-test-user-db/init.sql
  src/e2e/scala/temple/DSL/ParserE2ETest.scala
  src/it/scala/temple/generate/docker/DockerGeneratorIntegrationTestData.scala
  src/it/scala/temple/generate/server/GoGeneratorIntegrationTestData.scala
  src/main/scala/temple/DSL/semantics/Analyzer.scala
  src/main/scala/temple/DSL/semantics/ServiceRenamer.scala
  src/main/scala/temple/DSL/semantics/Validator.scala
  src/main/scala/temple/ast/AbstractAttribute.scala
  src/main/scala/temple/ast/AbstractServiceBlock.scala
  src/main/scala/temple/ast/Attribute.scala
  src/main/scala/temple/ast/AttributeBlock.scala
  src/main/scala/temple/ast/StructBlock.scala
  src/main/scala/temple/builder/DatabaseBuilder.scala
  src/main/scala/temple/builder/ServerBuilder.scala
  src/main/scala/temple/generate/server/ServiceRoot.scala
  src/main/scala/temple/generate/server/go/service/GoServiceHookGenerator.scala
  src/main/scala/temple/generate/server/go/service/dao/GoServiceDAOInputStructsGenerator.scala
  src/main/scala/temple/generate/server/go/service/main/GoServiceMainCreateHandlerGenerator.scala
  src/main/scala/temple/generate/server/go/service/main/GoServiceMainGenerator.scala
  src/main/scala/temple/generate/server/go/service/main/GoServiceMainHandlersGenerator.scala
  src/main/scala/temple/generate/server/go/service/main/GoServiceMainStructGenerator.scala
  src/main/scala/temple/generate/server/go/service/main/GoServiceMainUpdateHandlerGenerator.scala
  src/main/scala/temple/generate/target/openapi/OpenAPIGenerator.scala
  src/main/scala/temple/generate/target/openapi/ast/Service.scala
  src/main/scala/temple/test/internal/EndpointTest.scala
  src/main/scala/temple/test/internal/ServiceTestUtils.scala
  src/test/resources/project-builder-complex/api/sample-complex-project.openapi.yaml
  src/test/resources/project-builder-simple/api/sample-project.openapi.yaml
  src/test/scala/temple/DSL/semantics/SemanticAnalyzerTest.scala
  src/test/scala/temple/DSL/semantics/ValidatorTest.scala
  src/test/scala/temple/builder/BuilderTestData.scala
  src/test/scala/temple/builder/ServerBuilderTest.scala
  src/test/scala/temple/builder/project/ProjectBuilderTestData.scala
  src/test/scala/temple/detail/LanguageSpecificDetailBuilderTestData.scala
  src/test/scala/temple/generate/server/go/GoServiceGeneratorTestData.scala
  src/test/scala/temple/generate/target/openapi/OpenAPIGeneratorTest.scala
Labels: size/L

#268 [docker-compose gen] Allow docker-compose and kube in DSL
  src/main/scala/temple/ast/Metadata.scala
  src/test/scala/temple/DSL/semantics/ValidatorTest.scala
Labels: size/XXL

#270 [orchestration] Refactor into common parent package
  src/it/scala/temple/generate/orchestration/kube/KubernetesGeneratorIntegrationTest.scala
  src/it/scala/temple/generate/orchestration/kube/KubernetesGeneratorIntegrationTestData.scala
  src/main/scala/temple/builder/OrchestrationBuilder.scala
  src/main/scala/temple/builder/project/ProjectBuilder.scala
  src/main/scala/temple/builder/project/ProjectConfig.scala
  src/main/scala/temple/generate/orchestration/ast/OrchestrationType.scala
  src/main/scala/temple/generate/orchestration/dockercompose/DockerComposeGenerator.scala
  src/main/scala/temple/generate/orchestration/kube/DeployScriptGenerator.scala
  src/main/scala/temple/generate/orchestration/kube/GenType.scala
  src/main/scala/temple/generate/orchestration/kube/KongConfigGenerator.scala
  src/main/scala/temple/generate/orchestration/kube/KubernetesGenerator.scala
  src/main/scala/temple/generate/orchestration/kube/PushImageScriptGenerator.scala
  src/main/scala/temple/generate/orchestration/kube/ast/KubeType.scala
  src/main/scala/temple/generate/orchestration/kube/ast/LifecycleCommand.scala
  src/main/scala/temple/generate/orchestration/kube/ast/PlacementStrategy.scala
  src/main/scala/temple/generate/orchestration/kube/ast/RestartPolicy.scala
  src/main/scala/temple/generate/orchestration/kube/ast/Spec.scala
  src/main/scala/temple/generate/orchestration/kube/ast/volume/AccessMode.scala
  src/main/scala/temple/generate/orchestration/kube/ast/volume/ReclaimPolicy.scala
  src/main/scala/temple/generate/orchestration/kube/ast/volume/StorageClass.scala
  src/test/scala/temple/generate/orchestration/UnitTestData.scala
  src/test/scala/temple/generate/orchestration/dockercompose/DockerComposeGeneratorTest.scala
  src/test/scala/temple/generate/orchestration/kube/KongConfigGeneratorTest.scala
  src/test/scala/temple/generate/orchestration/kube/KubernetesGeneratorTest.scala
Labels: size/L

#269 [project-test] Fix issues from latest updates
  src/e2e/resources/simple-temple-expected/deploy.sh
  src/e2e/resources/simple-temple-expected/push-image.sh
  src/main/resources/shell/deploy.sh.deployment.snippet
  src/main/scala/temple/generate/orchestration/kube/PushImageScriptGenerator.scala
  src/main/scala/temple/test/ProjectTester.scala
  src/main/scala/temple/test/internal/CRUDServiceTest.scala
  src/main/scala/temple/test/internal/EndpointTest.scala
  src/main/scala/temple/test/internal/ServiceTestUtils.scala
  src/test/resources/project-builder-complex/deploy.sh
  src/test/resources/project-builder-complex/push-image.sh
  src/test/resources/project-builder-simple/deploy.sh
  src/test/resources/project-builder-simple/push-image.sh
  src/test/resources/shell/deploy-without-metrics.sh
  src/test/resources/shell/deploy.sh
Labels: size/L

#267 [Validator] Omit the update endpoint when there’s nothing to update
  src/e2e/resources/simple-temple-expected/api/simple-temple-test.openapi.yaml
  src/e2e/resources/simple-temple-expected/booking/booking.go
  src/e2e/resources/simple-temple-expected/booking/dao/dao.go
  src/e2e/resources/simple-temple-expected/booking/hook.go
  src/e2e/resources/simple-temple-expected/booking/metric/metric.go
  src/e2e/resources/simple-temple-expected/grafana/provisioning/dashboards/booking.json
  src/e2e/resources/simple-temple-expected/grafana/provisioning/dashboards/simple-temple-test-group.json
  src/e2e/resources/simple-temple-expected/simple-temple-test-group/dao/dao.go
  src/e2e/resources/simple-temple-expected/simple-temple-test-group/hook.go
  src/e2e/resources/simple-temple-expected/simple-temple-test-group/metric/metric.go
  src/e2e/resources/simple-temple-expected/simple-temple-test-group/simple-temple-test-group.go
  src/e2e/scala/temple/DSL/ParserE2ETest.scala
  src/main/scala/temple/Application.scala
  src/main/scala/temple/DSL/semantics/Validator.scala
  src/main/scala/temple/utils/FileUtils.scala
  src/test/scala/temple/DSL/semantics/ValidatorTest.scala
  src/test/scala/temple/builder/project/ProjectBuilderTest.scala
Labels: size/XL

#275 [docker-compose] Add support for services, databases and metrics
  src/main/scala/temple/generate/orchestration/dockercompose/DockerComposeGenerator.scala
  src/main/scala/temple/generate/orchestration/dockercompose/ast/DockerComposeRoot.scala
  src/main/scala/temple/generate/orchestration/dockercompose/ast/Service.scala
  src/test/resources/docker-compose/docker-compose-metrics.yml
  src/test/resources/docker-compose/docker-compose.yml
  src/test/scala/temple/generate/orchestration/dockercompose/DockerComposeGeneratorTest.scala
  src/test/scala/temple/generate/orchestration/dockercompose/DockerComposeGeneratorTestData.scala
Labels: size/L

#272 [Docker-Compose-Gen] Only generate kubernetes or docker compose when …
  src/e2e/scala/temple/DSL/ParserE2ETest.scala
  src/main/scala/temple/builder/project/ProjectBuilder.scala
  src/test/resources/project-builder-simple/deploy.sh
  src/test/resources/project-builder-simple/kong/configure-kong.sh
  src/test/resources/project-builder-simple/kube/deploy/deploy-daemon-set.yaml
  src/test/resources/project-builder-simple/kube/deploy/deploy-replication-controller.yaml
  src/test/resources/project-builder-simple/kube/deploy/deploy-service.yaml
  src/test/resources/project-builder-simple/kube/kong/kong-db-deployment.yaml
  src/test/resources/project-builder-simple/kube/kong/kong-db-service.yaml
  src/test/resources/project-builder-simple/kube/kong/kong-deployment.yaml
  src/test/resources/project-builder-simple/kube/kong/kong-migration-job.yaml
  src/test/resources/project-builder-simple/kube/kong/kong-service.yaml
  src/test/resources/project-builder-simple/kube/temple-user/db-deployment.yaml
  src/test/resources/project-builder-simple/kube/temple-user/db-service.yaml
  src/test/resources/project-builder-simple/kube/temple-user/db-storage.yaml
  src/test/resources/project-builder-simple/kube/temple-user/deployment.yaml
  src/test/resources/project-builder-simple/kube/temple-user/service.yaml
  src/test/resources/project-builder-simple/push-image.sh
  src/test/scala/temple/DSL/parser/DSLParserTest.scala
  src/test/scala/temple/builder/project/ProjectBuilderTestData.scala
  src/test/scala/temple/testfiles/simple.temple
Labels: size/XL

#274 [go-gen] Add generation of parsing time attributes in requests
  src/e2e/resources/simple-temple-expected/simple-temple-test-user/simple-temple-test-user.go
  src/main/scala/temple/generate/server/AuthServiceRoot.scala
  src/main/scala/temple/generate/server/IDAttribute.scala
  src/main/scala/temple/generate/server/go/auth/GoAuthServiceDAOGenerator.scala
  src/main/scala/temple/generate/server/go/common/GoCommonCommGenerator.scala
  src/main/scala/temple/generate/server/go/service/GoServiceCommGenerator.scala
  src/main/scala/temple/generate/server/go/service/GoServiceMetricGenerator.scala
  src/main/scala/temple/generate/server/go/service/dao/GoServiceDAOFunctionsGenerator.scala
  src/main/scala/temple/generate/server/go/service/main/GoServiceMainCreateHandlerGenerator.scala
  src/main/scala/temple/generate/server/go/service/main/GoServiceMainHandlersGenerator.scala
  src/main/scala/temple/generate/server/go/service/main/GoServiceMainStructGenerator.scala
  src/main/scala/temple/generate/server/go/service/main/GoServiceMainUpdateHandlerGenerator.scala
  src/test/resources/project-builder-complex/complex-user/complex-user.go
  src/test/resources/project-builder-simple/temple-user/temple-user.go
Labels: size/L

#276 [docker-compose] Generate kong scripts
  src/main/scala/temple/generate/orchestration/dockercompose/DockerComposeGenerator.scala
  src/main/scala/temple/generate/orchestration/dockercompose/ast/DockerComposeRoot.scala
  src/main/scala/temple/generate/orchestration/dockercompose/ast/kong/KongDatabase.scala
  src/main/scala/temple/generate/orchestration/dockercompose/ast/kong/KongMigrations.scala
  src/main/scala/temple/generate/orchestration/dockercompose/ast/kong/KongService.scala
  src/test/resources/docker-compose/docker-compose-metrics.yml
  src/test/resources/docker-compose/docker-compose.yml
Labels: size/L

#277 Auth docker compose
  src/it/scala/temple/generate/docker/DockerGeneratorIntegrationTest.scala
  src/main/resources/shell/wait-for-kong.sh
  src/main/scala/temple/builder/DockerfileBuilder.scala
  src/main/scala/temple/builder/project/ProjectBuilder.scala
  src/test/scala/temple/builder/DockerfileBuilderTest.scala
  src/test/scala/temple/builder/DockerfileBuilderTestData.scala
Labels: size/L

#278 [docker-compose] Generate kong config for docker compose
  src/main/scala/temple/generate/orchestration/KongConfigGenerator.scala
  src/main/scala/temple/generate/orchestration/dockercompose/DockerComposeGenerator.scala
  src/main/scala/temple/generate/orchestration/kube/KubernetesGenerator.scala
  src/test/scala/temple/generate/orchestration/kube/KongConfigGeneratorTest.scala
Labels: size/XS

#279 [endpoint-test] Support Docker Compose
  src/main/scala/temple/test/ProjectTester.scala
Labels: size/M

#280 [Docker-Compose-Gen] Deploy script generation DC
  src/main/resources/shell/deploy-docker-compose.sh
  src/main/scala/temple/generate/orchestration/dockercompose/DockerComposeGenerator.scala
  src/main/scala/temple/generate/orchestration/kube/DeployScriptGenerator.scala
  src/main/scala/temple/generate/orchestration/kube/KubernetesGenerator.scala
  src/test/resources/docker-compose/deploy.sh
  src/test/scala/temple/generate/orchestration/dockercompose/DockerComposeGeneratorTest.scala
  src/test/scala/temple/generate/orchestration/dockercompose/DockerComposeGeneratorTestData.scala
Labels: size/M

#283 [Tester] Add precision checks to temple-testing numerical fields
  src/main/scala/temple/test/internal/ServiceTestUtils.scala
Labels: size/XS

#284 [kong] Use -s flag in generated curl
  src/e2e/resources/simple-temple-expected/kong/configure-kong.sh
  src/main/scala/temple/generate/orchestration/KongConfigGenerator.scala
  src/test/resources/kong/configure-kong.sh
  src/test/resources/project-builder-complex/kong/configure-kong.sh
Labels: size/M

#281 [go-gen] Fix validation annotation
  src/e2e/resources/simple-temple-expected/simple-temple-test-user/simple-temple-test-user.go
  src/main/scala/temple/generate/server/go/service/main/GoServiceMainStructGenerator.scala
  src/test/resources/project-builder-complex/complex-user/complex-user.go
  src/test/resources/project-builder-simple/temple-user/temple-user.go
  src/test/scala/temple/generate/server/go/testfiles/match/match.go.snippet
  src/test/scala/temple/generate/server/go/testfiles/user/user.go.snippet
Labels: size/L

#285 [AST] Add attribute method for determining whether in request/response
  src/main/scala/temple/DSL/semantics/Validator.scala
  src/main/scala/temple/ast/AbstractAttribute.scala
  src/main/scala/temple/generate/server/go/service/GoServiceGenerator.scala
  src/main/scala/temple/generate/server/go/service/main/GoServiceMainHandlersGenerator.scala
  src/main/scala/temple/generate/server/go/service/main/GoServiceMainStructGenerator.scala
  src/main/scala/temple/generate/target/openapi/OpenAPIGenerator.scala
  src/main/scala/temple/test/internal/EndpointTest.scala
  src/main/scala/temple/test/internal/ServiceTestUtils.scala
Labels: size/M

#286 [project-test] Tidy output from tester
  src/main/scala/temple/test/ProjectTester.scala
  src/main/scala/temple/test/internal/AuthServiceTest.scala
  src/main/scala/temple/test/internal/CRUDServiceTest.scala
  src/main/scala/temple/test/internal/EndpointTest.scala
  src/main/scala/temple/test/internal/ServiceTest.scala
  src/test/scala/temple/testfiles/simple-dc.temple
Labels: size/M

#287 [go-gen] Add JSON annotations to req & resp structs
  src/e2e/resources/simple-temple-expected/booking/booking.go
  src/e2e/resources/simple-temple-expected/simple-temple-test-group/simple-temple-test-group.go
  src/e2e/resources/simple-temple-expected/simple-temple-test-user/simple-temple-test-user.go
  src/main/scala/temple/generate/server/go/service/main/GoServiceMainStructGenerator.scala
  src/main/scala/temple/utils/StringUtils.scala
  src/test/resources/project-builder-complex/complex-user/complex-user.go
  src/test/resources/project-builder-simple/temple-user/temple-user.go
  src/test/scala/temple/generate/server/go/testfiles/match/match.go.snippet
  src/test/scala/temple/generate/server/go/testfiles/user/user.go.snippet
Labels: size/L

#291 [project-test] Remove explicit ID check and make createdBy @server
  src/e2e/resources/simple-temple-expected/api/simple-temple-test.openapi.yaml
  src/main/scala/temple/ast/AbstractAttribute.scala
  src/main/scala/temple/test/internal/EndpointTest.scala
  src/main/scala/temple/test/internal/ServiceTestUtils.scala
  src/test/scala/temple/testfiles/simple-dc.temple
Labels: size/M

#293 [project-test] Improve equality testing of two attributes
  src/main/scala/temple/test/internal/EndpointTest.scala
Labels: size/L

#288 [Validator] Safe test number sizing
  src/main/scala/temple/DSL/semantics/Validator.scala
  src/main/scala/temple/ast/AttributeType.scala
  src/main/scala/temple/generate/target/openapi/OpenAPIGenerator.scala
  src/main/scala/temple/test/internal/ServiceTestUtils.scala
  src/test/scala/temple/DSL/semantics/ValidatorTest.scala
Labels: size/M

#299 [go-gen] Fix issue when generating only datetime
  src/it/scala/temple/generate/server/GoGeneratorIntegrationTest.scala
  src/it/scala/temple/generate/server/GoGeneratorIntegrationTestData.scala
  src/main/scala/temple/generate/server/go/service/main/GoServiceMainHandlersGenerator.scala
Labels: size/M

#295 [infra] Update temple test to allow templefiles without auth services
  src/main/scala/temple/test/ProjectTester.scala
  src/main/scala/temple/test/internal/CRUDServiceTest.scala
Labels: size/M

#297 [Validator] Add cycle detection to the validator, using Tarjan’s algo
  src/main/scala/temple/DSL/semantics/Tarjan.scala
  src/main/scala/temple/DSL/semantics/Validator.scala
  src/main/scala/temple/ast/Templefile.scala
  src/test/scala/temple/DSL/semantics/ValidatorTest.scala
Labels: size/L

#301 Comms set
  src/it/scala/temple/generate/server/GoGeneratorIntegrationTestData.scala
  src/main/scala/temple/builder/ServerBuilder.scala
  src/main/scala/temple/generate/server/ServiceRoot.scala
  src/main/scala/temple/generate/server/go/common/GoCommonGenerator.scala
  src/test/scala/temple/builder/BuilderTestData.scala
  src/test/scala/temple/builder/DatabaseBuilderTestData.scala
  src/test/scala/temple/builder/ServerBuilderTest.scala
  src/test/scala/temple/generate/server/go/GoServiceGeneratorTestData.scala
Labels: size/M

#302 [sql-gen] Use snake case for temple defined attributes
  src/e2e/resources/simple-temple-expected/booking-db/init.sql
  src/e2e/resources/simple-temple-expected/booking/dao/dao.go
  src/e2e/resources/simple-temple-expected/simple-temple-test-group-db/init.sql
  src/e2e/resources/simple-temple-expected/simple-temple-test-group/dao/dao.go
  src/e2e/resources/simple-temple-expected/simple-temple-test-user-db/init.sql
  src/e2e/scala/temple/DSL/ParserE2ETest.scala
  src/main/scala/temple/DSL/semantics/Validator.scala
Labels: size/M

#304 [project-test] Use temple test as an integration test
  src/it/scala/temple/EndpointIntegrationTest.scala
  src/it/scala/temple/containers/EndpointTesterSpec.scala
  src/it/scala/temple/containers/GolangSpec.scala
  src/it/scala/temple/containers/HadolintSpec.scala
  src/it/scala/temple/containers/KubeSpec.scala
  src/it/scala/temple/containers/SwaggerSpec.scala
  src/main/scala/temple/ast/AttributeType.scala
  src/main/scala/temple/test/ProjectTester.scala
Labels: size/M

#305 [go-gen] Add datastore interface to allow for extension
  src/e2e/resources/simple-temple-expected/auth/dao/dao.go
  src/e2e/resources/simple-temple-expected/auth/dao/datastore.go
  src/e2e/resources/simple-temple-expected/booking/dao/dao.go
  src/e2e/resources/simple-temple-expected/booking/dao/datastore.go
  src/e2e/resources/simple-temple-expected/simple-temple-test-group/dao/dao.go
  src/e2e/resources/simple-temple-expected/simple-temple-test-group/dao/datastore.go
  src/e2e/resources/simple-temple-expected/simple-temple-test-user/dao/dao.go
  src/e2e/resources/simple-temple-expected/simple-temple-test-user/dao/datastore.go
  src/main/scala/temple/generate/server/go/auth/GoAuthServiceDAOGenerator.scala
  src/main/scala/temple/generate/server/go/auth/GoAuthServiceGenerator.scala
  src/main/scala/temple/generate/server/go/common/GoCommonDAOGenerator.scala
  src/main/scala/temple/generate/server/go/service/GoServiceGenerator.scala
  src/main/scala/temple/generate/server/go/service/dao/GoServiceDAOInterfaceGenerator.scala
  src/test/resources/project-builder-complex/auth/dao/dao.go
  src/test/resources/project-builder-complex/auth/dao/datastore.go
  src/test/resources/project-builder-complex/complex-user/dao/dao.go
  src/test/resources/project-builder-complex/complex-user/dao/datastore.go
  src/test/resources/project-builder-simple/temple-user/dao/dao.go
  src/test/resources/project-builder-simple/temple-user/dao/datastore.go
  src/test/scala/temple/generate/server/go/GoAuthServiceGeneratorTestData.scala
  src/test/scala/temple/generate/server/go/GoServiceGeneratorTestData.scala
  src/test/scala/temple/generate/server/go/testfiles/auth/dao/dao.go.snippet
  src/test/scala/temple/generate/server/go/testfiles/auth/dao/datastore.go.snippet
  src/test/scala/temple/generate/server/go/testfiles/match/dao/dao.go.snippet
  src/test/scala/temple/generate/server/go/testfiles/match/dao/datastore.go.snippet
  src/test/scala/temple/generate/server/go/testfiles/user/dao/dao.go.snippet
  src/test/scala/temple/generate/server/go/testfiles/user/dao/datastore.go.snippet
Labels: size/L

#296 [go-gen] Fix interservice comms service names and config.json URL
  src/it/scala/temple/generate/server/GoGeneratorIntegrationTestData.scala
  src/main/scala/temple/builder/ServerBuilder.scala
  src/main/scala/temple/builder/project/ProjectBuilder.scala
  src/main/scala/temple/generate/server/ServiceName.scala
  src/main/scala/temple/generate/server/ServiceRoot.scala
  src/main/scala/temple/generate/server/go/auth/GoAuthServiceGenerator.scala
  src/main/scala/temple/generate/server/go/common/GoCommonMainGenerator.scala
  src/main/scala/temple/generate/server/go/service/GoServiceCommGenerator.scala
  src/test/scala/temple/builder/BuilderTestData.scala
  src/test/scala/temple/builder/ServerBuilderTest.scala
  src/test/scala/temple/builder/project/ProjectBuilderTestData.scala
  src/test/scala/temple/generate/server/go/GoServiceGeneratorTestData.scala
Labels: size/M

#303 [project-test] Add temple test for list endpoints
  src/main/scala/temple/test/internal/CRUDServiceTest.scala
Labels: size/M

#307 [go-gen] Add setup.go and invoke from main function
  src/e2e/resources/simple-temple-expected/auth/auth.go
  src/e2e/resources/simple-temple-expected/auth/setup.go
  src/e2e/resources/simple-temple-expected/booking/booking.go
  src/e2e/resources/simple-temple-expected/booking/setup.go
  src/e2e/resources/simple-temple-expected/simple-temple-test-group/setup.go
  src/e2e/resources/simple-temple-expected/simple-temple-test-group/simple-temple-test-group.go
  src/e2e/resources/simple-temple-expected/simple-temple-test-user/setup.go
  src/e2e/resources/simple-temple-expected/simple-temple-test-user/simple-temple-test-user.go
  src/main/resources/go/genFiles/auth/main/router.go.snippet
  src/main/scala/temple/generate/server/go/auth/GoAuthServiceGenerator.scala
  src/main/scala/temple/generate/server/go/common/GoCommonMainGenerator.scala
  src/main/scala/temple/generate/server/go/common/GoCommonSetupGenerator.scala
  src/main/scala/temple/generate/server/go/service/GoServiceGenerator.scala
  src/main/scala/temple/generate/server/go/service/main/GoServiceMainGenerator.scala
  src/test/resources/project-builder-complex/auth/auth.go
  src/test/resources/project-builder-complex/auth/setup.go
  src/test/resources/project-builder-complex/complex-user/complex-user.go
  src/test/resources/project-builder-complex/complex-user/setup.go
  src/test/resources/project-builder-simple/temple-user/setup.go
  src/test/resources/project-builder-simple/temple-user/temple-user.go
  src/test/scala/temple/generate/server/go/GoAuthServiceGeneratorTest.scala
  src/test/scala/temple/generate/server/go/GoAuthServiceGeneratorTestData.scala
  src/test/scala/temple/generate/server/go/GoServiceGeneratorTestData.scala
  src/test/scala/temple/generate/server/go/testfiles/auth/auth.go.snippet
  src/test/scala/temple/generate/server/go/testfiles/auth/setup.go.snippet
  src/test/scala/temple/generate/server/go/testfiles/match/match.go.snippet
  src/test/scala/temple/generate/server/go/testfiles/match/setup.go.snippet
  src/test/scala/temple/generate/server/go/testfiles/user/setup.go.snippet
  src/test/scala/temple/generate/server/go/testfiles/user/user.go.snippet
Labels: size/L

#306 [sql-gen] Snake case user provided attributes
  src/e2e/resources/simple-temple-expected/simple-temple-test-user-db/init.sql
  src/e2e/resources/simple-temple-expected/simple-temple-test-user/dao/dao.go
  src/main/scala/temple/builder/DatabaseBuilder.scala
  src/test/resources/project-builder-complex/complex-user-db/init.sql
  src/test/resources/project-builder-complex/complex-user/dao/dao.go
  src/test/resources/project-builder-simple/temple-user-db/init.sql
  src/test/resources/project-builder-simple/temple-user/dao/dao.go
  src/test/scala/temple/builder/DatabaseBuilderTestData.scala
Labels: size/L

#310 [Validator] [Analyzer] Boost coverage around validator and analyzer
  src/main/scala/temple/DSL/semantics/MetadataParser.scala
  src/main/scala/temple/DSL/semantics/Validator.scala
  src/test/scala/temple/DSL/semantics/ValidatorTest.scala
Labels: size/S

#308 [Codecov] Include e2e tests in the codecov report
  .travis.yml
Labels: size/XS

#309 [go-gen] Add hook object to environment
  src/e2e/resources/simple-temple-expected/auth/auth.go
  src/e2e/resources/simple-temple-expected/booking/booking.go
  src/e2e/resources/simple-temple-expected/simple-temple-test-group/simple-temple-test-group.go
  src/e2e/resources/simple-temple-expected/simple-temple-test-user/simple-temple-test-user.go
  src/main/resources/go/genFiles/auth/main/structs.go.snippet
  src/main/scala/temple/generate/server/go/common/GoCommonMainGenerator.scala
  src/main/scala/temple/generate/server/go/service/main/GoServiceMainStructGenerator.scala
  src/test/resources/project-builder-complex/auth/auth.go
  src/test/resources/project-builder-complex/complex-user/complex-user.go
  src/test/resources/project-builder-simple/temple-user/temple-user.go
  src/test/scala/temple/generate/server/go/testfiles/auth/auth.go.snippet
  src/test/scala/temple/generate/server/go/testfiles/match/match.go.snippet
  src/test/scala/temple/generate/server/go/testfiles/user/user.go.snippet
Labels: size/M

#312 [go-gen] Extract DAO input to separate variable
  src/e2e/resources/simple-temple-expected/booking/booking.go
  src/e2e/resources/simple-temple-expected/simple-temple-test-group/simple-temple-test-group.go
  src/e2e/resources/simple-temple-expected/simple-temple-test-user/simple-temple-test-user.go
  src/main/scala/temple/generate/server/go/service/main/GoServiceMainCreateHandlerGenerator.scala
  src/main/scala/temple/generate/server/go/service/main/GoServiceMainDeleteHandlerGenerator.scala
  src/main/scala/temple/generate/server/go/service/main/GoServiceMainGenerator.scala
  src/main/scala/temple/generate/server/go/service/main/GoServiceMainListHandlerGenerator.scala
  src/main/scala/temple/generate/server/go/service/main/GoServiceMainReadHandlerGenerator.scala
  src/main/scala/temple/generate/server/go/service/main/GoServiceMainUpdateHandlerGenerator.scala
  src/test/resources/project-builder-complex/complex-user/complex-user.go
  src/test/resources/project-builder-simple/temple-user/temple-user.go
  src/test/scala/temple/generate/server/go/testfiles/match/match.go.snippet
  src/test/scala/temple/generate/server/go/testfiles/user/user.go.snippet
Labels: size/L

#313 [go-gen] Extract auth DAO input to separate variable
  src/e2e/resources/simple-temple-expected/auth/auth.go
  src/main/resources/go/genFiles/auth/main/handlers.go.snippet
  src/test/resources/project-builder-complex/auth/auth.go
  src/test/scala/temple/generate/server/go/testfiles/auth/auth.go.snippet
Labels: size/M

#311 [go-gen] Make metric.go conditionally generated
  src/it/scala/temple/generate/server/GoGeneratorIntegrationTestData.scala
  src/main/scala/temple/builder/ServerBuilder.scala
  src/main/scala/temple/generate/server/AuthServiceRoot.scala
  src/main/scala/temple/generate/server/ServiceRoot.scala
  src/main/scala/temple/generate/server/go/auth/GoAuthServiceGenerator.scala
  src/main/scala/temple/generate/server/go/service/GoServiceGenerator.scala
  src/test/resources/project-builder-simple/temple-user/metric/metric.go
  src/test/scala/temple/builder/ServerBuilderTest.scala
  src/test/scala/temple/generate/server/go/GoAuthServiceGeneratorTestData.scala
  src/test/scala/temple/generate/server/go/GoServiceGeneratorTestData.scala
Labels: size/M

#315 Invoke hooks
  src/e2e/resources/simple-temple-expected/auth/auth.go
  src/e2e/resources/simple-temple-expected/booking/booking.go
  src/e2e/resources/simple-temple-expected/simple-temple-test-group/simple-temple-test-group.go
  src/e2e/resources/simple-temple-expected/simple-temple-test-user/simple-temple-test-user.go
  src/main/resources/go/genFiles/auth/main/handlers.go.snippet
  src/main/scala/temple/generate/server/go/service/main/GoServiceMainCreateHandlerGenerator.scala
  src/main/scala/temple/generate/server/go/service/main/GoServiceMainDeleteHandlerGenerator.scala
  src/main/scala/temple/generate/server/go/service/main/GoServiceMainHandlersGenerator.scala
  src/main/scala/temple/generate/server/go/service/main/GoServiceMainListHandlerGenerator.scala
  src/main/scala/temple/generate/server/go/service/main/GoServiceMainReadHandlerGenerator.scala
  src/main/scala/temple/generate/server/go/service/main/GoServiceMainUpdateHandlerGenerator.scala
  src/test/resources/project-builder-complex/auth/auth.go
  src/test/resources/project-builder-complex/complex-user/complex-user.go
  src/test/resources/project-builder-simple/temple-user/temple-user.go
  src/test/scala/temple/generate/server/go/testfiles/auth/auth.go.snippet
  src/test/scala/temple/generate/server/go/testfiles/match/match.go.snippet
  src/test/scala/temple/generate/server/go/testfiles/user/user.go.snippet
Labels: size/L

#316 [go-gen] Add generation of metric server instantiation in main, and refactor main gen
  docker/deploy.sh
  docker/shell2http.Dockerfile
  src/e2e/resources/simple-temple-expected/auth/auth.go
  src/e2e/resources/simple-temple-expected/auth/util/util.go
  src/e2e/resources/simple-temple-expected/booking/booking.go
  src/e2e/resources/simple-temple-expected/booking/util/util.go
  src/e2e/resources/simple-temple-expected/simple-temple-test-group/simple-temple-test-group.go
  src/e2e/resources/simple-temple-expected/simple-temple-test-group/util/util.go
  src/e2e/resources/simple-temple-expected/simple-temple-test-user/simple-temple-test-user.go
  src/e2e/resources/simple-temple-expected/simple-temple-test-user/util/util.go
  src/it/scala/temple/containers/DockerShell2HttpService.scala
  src/main/resources/go/genFiles/common/util/config_struct.go.snippet
  src/main/scala/temple/generate/server/ServiceRoot.scala
  src/main/scala/temple/generate/server/go/auth/GoAuthServiceGenerator.scala
  src/main/scala/temple/generate/server/go/auth/GoAuthServiceMainGenerator.scala
  src/main/scala/temple/generate/server/go/common/GoCommonGenerator.scala
  src/main/scala/temple/generate/server/go/common/GoCommonMainGenerator.scala
  src/main/scala/temple/generate/server/go/service/GoServiceGenerator.scala
  src/main/scala/temple/generate/server/go/service/main/GoServiceMainGenerator.scala
  src/test/resources/project-builder-complex/auth/auth.go
  src/test/resources/project-builder-complex/auth/util/util.go
  src/test/resources/project-builder-complex/complex-user/complex-user.go
  src/test/resources/project-builder-complex/complex-user/util/util.go
  src/test/resources/project-builder-simple/temple-user/util/util.go
  src/test/scala/temple/generate/server/go/testfiles/auth/auth.go.snippet
  src/test/scala/temple/generate/server/go/testfiles/auth/util/util.go.snippet
  src/test/scala/temple/generate/server/go/testfiles/match/match.go.snippet
  src/test/scala/temple/generate/server/go/testfiles/match/util/util.go.snippet
  src/test/scala/temple/generate/server/go/testfiles/user/user.go.snippet
  src/test/scala/temple/generate/server/go/testfiles/user/util/util.go.snippet
Labels: size/L

#314 [Semantics] Make lookupMetadata more typesafe: limit to project metadata
  src/e2e/resources/simple-temple-expected/grafana/provisioning/dashboards/simple-temple-test-user.json
  src/main/scala/temple/ast/TempleBlock.scala
  src/main/scala/temple/ast/TempleNode.scala
  src/main/scala/temple/ast/Templefile.scala
  src/main/scala/temple/builder/ServerBuilder.scala
  src/main/scala/temple/builder/project/ProjectBuilder.scala
  src/main/scala/temple/test/ProjectTester.scala
  src/main/scala/temple/test/internal/AuthServiceTest.scala
  src/main/scala/temple/test/internal/ServiceTestUtils.scala
  src/test/scala/temple/DSL/semantics/TempleBlockTest.scala
Labels: size/L

#317 [config] Remove Prometheus port if no metrics requested
  src/main/scala/temple/builder/project/ProjectBuilder.scala
  src/main/scala/temple/generate/server/config/ServerConfigGenerator.scala
  src/main/scala/temple/generate/server/config/ast/ServerConfig.scala
  src/test/resources/project-builder-simple/temple-user/config.json
  src/test/scala/temple/builder/project/ProjectBuilderTestData.scala
  src/test/scala/temple/generate/server/config/ServerConfigGeneratorTest.scala
  src/test/scala/temple/generate/server/config/ServerConfigGeneratorTestData.scala
Labels: size/M

#318 After hook invoke
  src/e2e/resources/simple-temple-expected/auth/auth.go
  src/e2e/resources/simple-temple-expected/booking/booking.go
  src/e2e/resources/simple-temple-expected/simple-temple-test-group/simple-temple-test-group.go
  src/e2e/resources/simple-temple-expected/simple-temple-test-user/simple-temple-test-user.go
  src/main/resources/go/genFiles/auth/main/handlers.go.snippet
  src/main/scala/temple/generate/server/go/service/main/GoServiceMainCreateHandlerGenerator.scala
  src/main/scala/temple/generate/server/go/service/main/GoServiceMainDeleteHandlerGenerator.scala
  src/main/scala/temple/generate/server/go/service/main/GoServiceMainHandlersGenerator.scala
  src/main/scala/temple/generate/server/go/service/main/GoServiceMainListHandlerGenerator.scala
  src/main/scala/temple/generate/server/go/service/main/GoServiceMainReadHandlerGenerator.scala
  src/main/scala/temple/generate/server/go/service/main/GoServiceMainUpdateHandlerGenerator.scala
  src/test/resources/project-builder-complex/auth/auth.go
  src/test/resources/project-builder-complex/complex-user/complex-user.go
  src/test/resources/project-builder-simple/temple-user/temple-user.go
  src/test/scala/temple/generate/server/go/testfiles/auth/auth.go.snippet
  src/test/scala/temple/generate/server/go/testfiles/match/match.go.snippet
  src/test/scala/temple/generate/server/go/testfiles/user/user.go.snippet
Labels: size/L

#321 [go-gen] Add generation of timing and request success metrics
  src/e2e/resources/simple-temple-expected/auth/auth.go
  src/e2e/resources/simple-temple-expected/booking/booking.go
  src/e2e/resources/simple-temple-expected/simple-temple-test-group/simple-temple-test-group.go
  src/e2e/resources/simple-temple-expected/simple-temple-test-user/simple-temple-test-user.go
  src/main/resources/go/genFiles/auth/main/handlers.go.snippet
  src/main/scala/temple/generate/server/go/auth/GoAuthServiceMainGenerator.scala
  src/main/scala/temple/generate/server/go/common/GoCommonMainGenerator.scala
  src/main/scala/temple/generate/server/go/service/GoServiceGenerator.scala
  src/main/scala/temple/generate/server/go/service/main/GoServiceMainCreateHandlerGenerator.scala
  src/main/scala/temple/generate/server/go/service/main/GoServiceMainDeleteHandlerGenerator.scala
  src/main/scala/temple/generate/server/go/service/main/GoServiceMainGenerator.scala
  src/main/scala/temple/generate/server/go/service/main/GoServiceMainHandlersGenerator.scala
  src/main/scala/temple/generate/server/go/service/main/GoServiceMainListHandlerGenerator.scala
  src/main/scala/temple/generate/server/go/service/main/GoServiceMainReadHandlerGenerator.scala
  src/main/scala/temple/generate/server/go/service/main/GoServiceMainUpdateHandlerGenerator.scala
  src/test/resources/project-builder-complex/auth/auth.go
  src/test/resources/project-builder-complex/complex-user/complex-user.go
  src/test/scala/temple/generate/server/go/testfiles/auth/auth.go.snippet
  src/test/scala/temple/generate/server/go/testfiles/match/match.go.snippet
  src/test/scala/temple/generate/server/go/testfiles/user/user.go.snippet
Labels: size/L

#319 [DSL] Move auth method to be specified in the project block
  src/e2e/scala/temple/DSL/ParserE2ETest.scala
  src/main/scala/temple/DSL/semantics/Analyzer.scala
  src/main/scala/temple/DSL/semantics/ServiceRenamer.scala
  src/main/scala/temple/DSL/semantics/Validator.scala
  src/main/scala/temple/ast/Metadata.scala
  src/main/scala/temple/ast/TempleBlock.scala
  src/main/scala/temple/ast/Templefile.scala
  src/main/scala/temple/builder/ServerBuilder.scala
  src/main/scala/temple/builder/project/ProjectBuilder.scala
  src/main/scala/temple/builder/project/ProjectConfig.scala
  src/main/scala/temple/generate/server/AuthAttribute.scala
  src/main/scala/temple/generate/server/go/auth/GoAuthServiceDAOGenerator.scala
  src/main/scala/temple/test/ProjectTester.scala
  src/main/scala/temple/test/internal/AuthServiceTest.scala
  src/test/scala/temple/DSL/parser/DSLParserTest.scala
  src/test/scala/temple/DSL/semantics/SemanticAnalyzerTest.scala
  src/test/scala/temple/DSL/semantics/ValidatorTest.scala
  src/test/scala/temple/builder/DockerfileBuilderTest.scala
  src/test/scala/temple/builder/ServerBuilderTest.scala
  src/test/scala/temple/builder/project/ProjectBuilderTestData.scala
  src/test/scala/temple/generate/server/go/GoAuthServiceGeneratorTestData.scala
  src/test/scala/temple/testfiles/simple-dc.temple
  src/test/scala/temple/testfiles/simple.temple
Labels: size/L

#320 [it-test] Add examples folder and use in integration test
  examples/tinder.temple
  src/it/scala/temple/EndpointIntegrationTest.scala
Labels: size/M

#325 [go-gen] Add respondWithError function gen, and use in auth service
  src/e2e/resources/simple-temple-expected/auth/auth.go
  src/e2e/resources/simple-temple-expected/booking/booking.go
  src/e2e/resources/simple-temple-expected/simple-temple-test-group/simple-temple-test-group.go
  src/e2e/resources/simple-temple-expected/simple-temple-test-user/simple-temple-test-user.go
  src/main/resources/go/genFiles/auth/main/handlers-metric.go.snippet
  src/main/resources/go/genFiles/auth/main/handlers-no-metric.go.snippet
  src/main/scala/temple/generate/server/go/auth/GoAuthServiceGenerator.scala
  src/main/scala/temple/generate/server/go/auth/GoAuthServiceMainGenerator.scala
  src/main/scala/temple/generate/server/go/common/GoCommonMainGenerator.scala
  src/main/scala/temple/generate/server/go/service/GoServiceGenerator.scala
  src/main/scala/temple/generate/server/go/service/main/GoServiceMainGenerator.scala
  src/test/resources/project-builder-complex/auth/auth.go
  src/test/resources/project-builder-complex/complex-user/complex-user.go
  src/test/resources/project-builder-simple/temple-user/temple-user.go
  src/test/scala/temple/generate/server/go/testfiles/auth/auth.go.snippet
  src/test/scala/temple/generate/server/go/testfiles/match/match.go.snippet
  src/test/scala/temple/generate/server/go/testfiles/user/user.go.snippet
Labels: size/L

#326 [openapi-gen] Add identity endpoint
  src/it/scala/temple/generate/target/openapi/OpenAPIGeneratorIntegrationTest.scala
  src/main/scala/temple/generate/CRUD.scala
  src/main/scala/temple/generate/target/openapi/OpenAPIGenerator.scala
  src/main/scala/temple/generate/target/openapi/ast/HeaderObject.scala
  src/main/scala/temple/generate/target/openapi/ast/RequestBodyObject.scala
  src/main/scala/temple/generate/target/openapi/ast/ResponseObject.scala
  src/test/scala/temple/DSL/semantics/NameClashesTest.scala
  src/test/scala/temple/generate/target/openapi/OpenAPIGeneratorTest.scala
Labels: size/L

#324 [Go-gen] Move ServiceRoot to a trait in preparation for StructRoot
  src/e2e/resources/simple-temple-expected/simple-temple-test-user/dao/dao.go
  src/it/scala/temple/generate/server/GoGeneratorIntegrationTestData.scala
  src/main/scala/temple/builder/DatabaseBuilder.scala
  src/main/scala/temple/builder/ServerBuilder.scala
  src/main/scala/temple/generate/server/AbstractAttributesRoot.scala
  src/main/scala/temple/generate/server/AttributesRoot.scala
  src/main/scala/temple/generate/server/AuthServiceRoot.scala
  src/main/scala/temple/generate/server/ServiceGenerator.scala
  src/main/scala/temple/generate/server/ServiceName.scala
  src/main/scala/temple/generate/server/ServiceRoot.scala
  src/main/scala/temple/generate/server/go/auth/GoAuthServiceGenerator.scala
  src/main/scala/temple/generate/server/go/common/GoCommonMainGenerator.scala
  src/main/scala/temple/generate/server/go/service/GoServiceCommGenerator.scala
  src/main/scala/temple/generate/server/go/service/GoServiceGenerator.scala
  src/main/scala/temple/generate/server/go/service/GoServiceHookGenerator.scala
  src/main/scala/temple/generate/server/go/service/GoServiceMetricGenerator.scala
  src/main/scala/temple/generate/server/go/service/dao/GoServiceDAOFunctionsGenerator.scala
  src/main/scala/temple/generate/server/go/service/dao/GoServiceDAOGenerator.scala
  src/main/scala/temple/generate/server/go/service/dao/GoServiceDAOInputStructsGenerator.scala
  src/main/scala/temple/generate/server/go/service/dao/GoServiceDAOInterfaceGenerator.scala
  src/main/scala/temple/generate/server/go/service/main/GoServiceMainCreateHandlerGenerator.scala
  src/main/scala/temple/generate/server/go/service/main/GoServiceMainDeleteHandlerGenerator.scala
  src/main/scala/temple/generate/server/go/service/main/GoServiceMainGenerator.scala
  src/main/scala/temple/generate/server/go/service/main/GoServiceMainHandlersGenerator.scala
  src/main/scala/temple/generate/server/go/service/main/GoServiceMainListHandlerGenerator.scala
  src/main/scala/temple/generate/server/go/service/main/GoServiceMainReadHandlerGenerator.scala
  src/main/scala/temple/generate/server/go/service/main/GoServiceMainStructGenerator.scala
  src/main/scala/temple/generate/server/go/service/main/GoServiceMainUpdateHandlerGenerator.scala
  src/test/scala/temple/builder/ServerBuilderTest.scala
  src/test/scala/temple/generate/server/go/GoServiceGeneratorTestData.scala
Labels: size/L

#322 [Kube-Gen] Generate Grafana and Prom Scripts in Kubernetes
  src/e2e/resources/simple-temple-expected/kube/auth/deployment.yaml
  src/e2e/resources/simple-temple-expected/kube/auth/service.yaml
  src/e2e/resources/simple-temple-expected/kube/booking/deployment.yaml
  src/e2e/resources/simple-temple-expected/kube/booking/service.yaml
  src/e2e/resources/simple-temple-expected/kube/grafana/grafana-deployment.yaml
  src/e2e/resources/simple-temple-expected/kube/grafana/grafana-service.yaml
  src/e2e/resources/simple-temple-expected/kube/prom/prometheus-deployment.yaml
  src/e2e/resources/simple-temple-expected/kube/prom/prometheus-service.yaml
  src/e2e/resources/simple-temple-expected/kube/simple-temple-test-group/deployment.yaml
  src/e2e/resources/simple-temple-expected/kube/simple-temple-test-group/service.yaml
  src/e2e/resources/simple-temple-expected/kube/simple-temple-test-user/deployment.yaml
  src/e2e/resources/simple-temple-expected/kube/simple-temple-test-user/service.yaml
  src/it/scala/temple/generate/orchestration/kube/KubernetesGeneratorIntegrationTestData.scala
  src/main/resources/kube/metric/grafana-service.yaml
  src/main/resources/kube/metric/prometheus-deployment.yaml
  src/main/resources/kube/metric/prometheus-service.yaml
  src/main/scala/temple/ast/Templefile.scala
  src/main/scala/temple/builder/OrchestrationBuilder.scala
  src/main/scala/temple/builder/project/ProjectBuilder.scala
  src/main/scala/temple/builder/project/ProjectConfig.scala
  src/main/scala/temple/generate/orchestration/KongConfigGenerator.scala
  src/main/scala/temple/generate/orchestration/ast/OrchestrationType.scala
  src/main/scala/temple/generate/orchestration/dockercompose/DockerComposeGenerator.scala
  src/main/scala/temple/generate/orchestration/kube/GenType.scala
  src/main/scala/temple/generate/orchestration/kube/KubernetesGenerator.scala
  src/main/scala/temple/generate/orchestration/kube/KubernetesMetricGenerator.scala
  src/test/resources/docker-compose/docker-compose-metrics.yml
  src/test/resources/docker-compose/docker-compose.yml
  src/test/resources/kube/user-deployment.yaml
  src/test/resources/kube/user-grafana-deployment.yaml
  src/test/resources/kube/user-service.yaml
  src/test/resources/project-builder-complex/kube/auth/deployment.yaml
  src/test/resources/project-builder-complex/kube/auth/service.yaml
  src/test/resources/project-builder-complex/kube/complex-user/deployment.yaml
  src/test/resources/project-builder-complex/kube/complex-user/service.yaml
  src/test/resources/project-builder-complex/kube/grafana/grafana-deployment.yaml
  src/test/resources/project-builder-complex/kube/grafana/grafana-service.yaml
  src/test/resources/project-builder-complex/kube/prom/prometheus-deployment.yaml
  src/test/resources/project-builder-complex/kube/prom/prometheus-service.yaml
  src/test/scala/temple/generate/orchestration/UnitTestData.scala
  src/test/scala/temple/generate/orchestration/kube/KubernetesGeneratorTest.scala
Labels: size/L

#328 [go-gen] Add respondWithError to non-auth handlers
  src/e2e/resources/simple-temple-expected/booking/booking.go
  src/e2e/resources/simple-temple-expected/simple-temple-test-group/simple-temple-test-group.go
  src/e2e/resources/simple-temple-expected/simple-temple-test-user/simple-temple-test-user.go
  src/main/scala/temple/generate/server/go/auth/GoAuthServiceGenerator.scala
  src/main/scala/temple/generate/server/go/common/GoCommonGenerator.scala
  src/main/scala/temple/generate/server/go/common/GoCommonMainGenerator.scala
  src/main/scala/temple/generate/server/go/service/GoServiceGenerator.scala
  src/main/scala/temple/generate/server/go/service/main/GoServiceMainCreateHandlerGenerator.scala
  src/main/scala/temple/generate/server/go/service/main/GoServiceMainDeleteHandlerGenerator.scala
  src/main/scala/temple/generate/server/go/service/main/GoServiceMainHandlersGenerator.scala
  src/main/scala/temple/generate/server/go/service/main/GoServiceMainListHandlerGenerator.scala
  src/main/scala/temple/generate/server/go/service/main/GoServiceMainReadHandlerGenerator.scala
  src/main/scala/temple/generate/server/go/service/main/GoServiceMainUpdateHandlerGenerator.scala
  src/test/resources/project-builder-complex/complex-user/complex-user.go
  src/test/resources/project-builder-simple/temple-user/temple-user.go
  src/test/scala/temple/generate/server/go/testfiles/match/match.go.snippet
  src/test/scala/temple/generate/server/go/testfiles/user/user.go.snippet
Labels: size/XL

#327 [go-gen] Add identify endpoint
  src/e2e/resources/simple-temple-expected/api/simple-temple-test.openapi.yaml
  src/e2e/resources/simple-temple-expected/grafana/provisioning/dashboards/simple-temple-test-user.json
  src/e2e/resources/simple-temple-expected/simple-temple-test-user/dao/dao.go
  src/e2e/resources/simple-temple-expected/simple-temple-test-user/hook.go
  src/e2e/resources/simple-temple-expected/simple-temple-test-user/metric/metric.go
  src/e2e/resources/simple-temple-expected/simple-temple-test-user/simple-temple-test-user.go
  src/main/scala/temple/builder/DatabaseBuilder.scala
  src/main/scala/temple/builder/MetricsBuilder.scala
  src/main/scala/temple/builder/ServerBuilder.scala
  src/main/scala/temple/builder/project/ProjectBuilder.scala
  src/main/scala/temple/generate/CRUD.scala
  src/main/scala/temple/generate/server/go/service/GoServiceHookGenerator.scala
  src/main/scala/temple/generate/server/go/service/dao/GoServiceDAOFunctionsGenerator.scala
  src/main/scala/temple/generate/server/go/service/dao/GoServiceDAOInputStructsGenerator.scala
  src/main/scala/temple/generate/server/go/service/dao/GoServiceDAOInterfaceGenerator.scala
  src/main/scala/temple/generate/server/go/service/main/GoServiceMainGenerator.scala
  src/main/scala/temple/generate/server/go/service/main/GoServiceMainHandlersGenerator.scala
  src/main/scala/temple/generate/server/go/service/main/GoServiceMainIdentityHandlerGenerator.scala
  src/main/scala/temple/generate/target/openapi/OpenAPIGenerator.scala
  src/main/scala/temple/test/internal/CRUDServiceTest.scala
  src/test/resources/project-builder-complex/api/sample-complex-project.openapi.yaml
  src/test/resources/project-builder-complex/complex-user/complex-user.go
  src/test/resources/project-builder-complex/complex-user/dao/dao.go
  src/test/resources/project-builder-complex/complex-user/hook.go
  src/test/resources/project-builder-complex/complex-user/metric/metric.go
  src/test/resources/project-builder-complex/grafana/provisioning/dashboards/complex-user.json
  src/test/scala/temple/DSL/semantics/NameClashesTest.scala
  src/test/scala/temple/builder/ServerBuilderTest.scala
Labels: size/XL

#329 [Validator] Reword misleading error message when a name clashes
  src/main/scala/temple/DSL/semantics/NameClashes.scala
  src/test/scala/temple/DSL/semantics/NameClashesTest.scala
Labels: size/XS

#331 [Validator] Correct casing of createdBy
  src/e2e/scala/temple/DSL/ParserE2ETest.scala
  src/main/scala/temple/DSL/semantics/Validator.scala
Labels: size/S

#330 [go-gen] Uncurry generateRespondWithError
  src/main/scala/temple/generate/server/go/service/main/GoServiceMainCreateHandlerGenerator.scala
  src/main/scala/temple/generate/server/go/service/main/GoServiceMainHandlersGenerator.scala
  src/main/scala/temple/generate/server/go/service/main/GoServiceMainListHandlerGenerator.scala
Labels: size/M

#332 [DSL] Remove nullable
  src/e2e/resources/simple-temple-expected/simple-temple-test-user-db/init.sql
  src/e2e/scala/temple/DSL/ParserE2ETest.scala
  src/it/scala/temple/generate/docker/DockerGeneratorIntegrationTestData.scala
  src/main/scala/temple/DSL/semantics/Analyzer.scala
  src/main/scala/temple/DSL/semantics/Validator.scala
  src/main/scala/temple/ast/Annotation.scala
  src/main/scala/temple/builder/DatabaseBuilder.scala
  src/test/scala/temple/DSL/parser/DSLParserTest.scala
  src/test/scala/temple/DSL/semantics/SemanticAnalyzerTest.scala
  src/test/scala/temple/DSL/semantics/ValidatorTest.scala
  src/test/scala/temple/builder/BuilderTestData.scala
  src/test/scala/temple/builder/DatabaseBuilderTestData.scala
  src/test/scala/temple/testfiles/simple-dc.temple
  src/test/scala/temple/testfiles/simple.temple
Labels: size/M

#335 [go-gen] Add identify handler
  src/e2e/resources/simple-temple-expected/api/simple-temple-test.openapi.yaml
  src/e2e/resources/simple-temple-expected/simple-temple-test-user/simple-temple-test-user.go
  src/main/scala/temple/generate/server/go/service/main/GoServiceMainHandlersGenerator.scala
  src/main/scala/temple/generate/server/go/service/main/GoServiceMainIdentifyHandlerGenerator.scala
  src/main/scala/temple/generate/server/go/service/main/GoServiceMainIdentityHandlerGenerator.scala
  src/main/scala/temple/generate/target/openapi/OpenAPIGenerator.scala
  src/test/resources/project-builder-complex/api/sample-complex-project.openapi.yaml
  src/test/resources/project-builder-complex/complex-user/complex-user.go
  src/test/scala/temple/generate/target/openapi/OpenAPIGeneratorTest.scala
Labels: size/L

#336 [CLI] Give better error messages when the CLI crashes
  src/main/scala/temple/Main.scala
Labels: size/XS

#334 [go-gen] Fix list DAO request query arguments
  src/it/scala/temple/EndpointIntegrationTest.scala
  src/main/scala/temple/generate/server/go/service/dao/GoServiceDAOFunctionsGenerator.scala
  src/test/scala/temple/testfiles/enumReadAll.temple
Labels: size/M

#338 [project-test] Use identify endpoint to avoid access token logic
  src/main/scala/temple/test/internal/CRUDServiceTest.scala
  src/main/scala/temple/test/internal/ServiceTestUtils.scala
Labels: size/L

#341 [project-test] Add explict test for identify endpoint
  src/main/scala/temple/test/internal/CRUDServiceTest.scala
Labels: size/S

#342 [examples] Add amazon example
  examples/amazon.temple
Labels: size/M

#346 [Go-gen] Fix detection of base64 code
  src/main/scala/temple/generate/server/go/service/GoServiceGenerator.scala
Labels: size/XS

#344 [Validator] Validate that a struct cannot be more readable than its service
  src/main/scala/temple/DSL/semantics/Validator.scala
  src/test/scala/temple/DSL/semantics/ValidatorTest.scala
Labels: size/M

#345 [grafana] Fix ordering of grafana
  src/e2e/resources/simple-temple-expected/grafana/provisioning/dashboards/simple-temple-test-user.json
  src/main/scala/temple/builder/MetricsBuilder.scala
  src/test/resources/project-builder-complex/grafana/provisioning/dashboards/complex-user.json
Labels: size/L

#347 [DSL] Remove access controls from structs
  src/e2e/scala/temple/DSL/ParserE2ETest.scala
  src/main/scala/temple/DSL/semantics/Analyzer.scala
  src/main/scala/temple/DSL/semantics/Validator.scala
  src/main/scala/temple/ast/Metadata.scala
  src/test/scala/temple/DSL/parser/DSLParserTest.scala
  src/test/scala/temple/DSL/semantics/ValidatorTest.scala
  src/test/scala/temple/testfiles/simple-dc.temple
  src/test/scala/temple/testfiles/simple.temple
Labels: size/M

#343 [Regen] Implement Regeneration
  src/e2e/scala/temple/SimpleE2ETest.scala
  src/main/scala/temple/Application.scala
  src/main/scala/temple/RegenerationFilter.scala
  src/main/scala/temple/utils/FileUtils.scala
  src/test/scala/temple/RegenerationFilterTest.scala
  src/test/scala/temple/RegenerationFilterTestData.scala
  src/test/scala/temple/TestUtils.scala
  src/test/scala/temple/builder/project/ProjectBuilderTest.scala
  src/test/scala/temple/detail/PoliceSergeantNicholasAngel.scala
  src/test/scala/temple/generate/server/go/GoAuthServiceGeneratorTestData.scala
  src/test/scala/temple/generate/server/go/GoServiceGeneratorTestData.scala
Labels: size/L

#348 [go-gen] Fix implementation of blob types
  src/it/scala/temple/EndpointIntegrationTest.scala
  src/it/scala/temple/generate/server/GoGeneratorIntegrationTest.scala
  src/it/scala/temple/generate/server/GoGeneratorIntegrationTestData.scala
  src/main/scala/temple/generate/server/go/common/GoCommonGenerator.scala
  src/main/scala/temple/generate/server/go/service/main/GoServiceMainCreateHandlerGenerator.scala
  src/main/scala/temple/generate/server/go/service/main/GoServiceMainHandlersGenerator.scala
  src/main/scala/temple/generate/server/go/service/main/GoServiceMainUpdateHandlerGenerator.scala
  src/test/resources/project-builder-complex/complex-user/complex-user.go
  src/test/resources/project-builder-simple/temple-user/temple-user.go
  src/test/scala/temple/testfiles/data.temple
Labels: size/L

#349 [go-gen] Use %s in error format string
  src/e2e/resources/simple-temple-expected/booking/dao/errors.go
  src/e2e/resources/simple-temple-expected/simple-temple-test-group/dao/errors.go
  src/e2e/resources/simple-temple-expected/simple-temple-test-user/dao/errors.go
  src/main/scala/temple/generate/server/go/service/dao/GoServiceDAOGenerator.scala
  src/test/resources/generate-server-test/match/dao/errors.go
  src/test/resources/generate-server-test/user/dao/errors.go
  src/test/resources/project-builder-complex/complex-user/dao/errors.go
  src/test/resources/project-builder-simple/temple-user/dao/errors.go
Labels: size/S

#355 [test] Validate kong has been correctly setup when no auth block is present
  src/main/scala/temple/test/ProjectTester.scala
Labels: size/S

#340 [Go-gen] Add spacing inside Hook type to match spec-golang
  src/e2e/resources/simple-temple-expected/auth/hook.go
  src/e2e/resources/simple-temple-expected/booking/hook.go
  src/e2e/resources/simple-temple-expected/simple-temple-test-group/hook.go
  src/e2e/resources/simple-temple-expected/simple-temple-test-user/hook.go
  src/main/scala/temple/generate/server/go/auth/GoAuthServiceDAOGenerator.scala
  src/main/scala/temple/generate/server/go/auth/GoAuthServiceHookGenerator.scala
  src/main/scala/temple/generate/server/go/common/GoCommonGenerator.scala
  src/main/scala/temple/generate/server/go/service/GoServiceHookGenerator.scala
  src/test/resources/generate-server-test/auth/hook.go
  src/test/resources/generate-server-test/match/hook.go
  src/test/resources/generate-server-test/user/hook.go
  src/test/resources/project-builder-complex/auth/hook.go
  src/test/resources/project-builder-complex/complex-user/hook.go
  src/test/resources/project-builder-simple/temple-user/hook.go
Labels: size/L

#350 [examples] Add Airbnb templefile
  examples/airbnb.temple
Labels: size/M

#351 [metrics] Fix prom address and auth metric names
  src/e2e/resources/simple-temple-expected/grafana/provisioning/dashboards/auth.json
  src/e2e/resources/simple-temple-expected/grafana/provisioning/datasources/datasource.yml
  src/main/scala/temple/builder/MetricsBuilder.scala
  src/main/scala/temple/builder/project/ProjectBuilder.scala
  src/test/resources/project-builder-complex/grafana/provisioning/dashboards/auth.json
  src/test/resources/project-builder-complex/grafana/provisioning/datasources/datasource.yml
Labels: size/L

#353 [go-gen] Include leading http in response header
  src/e2e/resources/simple-temple-expected/simple-temple-test-user/simple-temple-test-user.go
  src/main/scala/temple/generate/server/go/service/main/GoServiceMainIdentifyHandlerGenerator.scala
  src/main/scala/temple/test/internal/CRUDServiceTest.scala
  src/main/scala/temple/test/internal/ServiceTestUtils.scala
  src/test/resources/project-builder-complex/complex-user/complex-user.go
Labels: size/S

#354 [test] Allow --testOnly flag to temple test
  src/main/scala/temple/Application.scala
  src/main/scala/temple/TempleConfig.scala
  src/main/scala/temple/test/ProjectTester.scala
Labels: size/M

#352 [examples] Add 5-a-side templefile
  examples/five-a-side.templefile
Labels: size/M

#356 [go-gen] Add auth arg to hooks
  src/e2e/resources/simple-temple-expected/booking/booking.go
  src/e2e/resources/simple-temple-expected/booking/hook.go
  src/e2e/resources/simple-temple-expected/simple-temple-test-group/hook.go
  src/e2e/resources/simple-temple-expected/simple-temple-test-group/simple-temple-test-group.go
  src/e2e/resources/simple-temple-expected/simple-temple-test-user/hook.go
  src/e2e/resources/simple-temple-expected/simple-temple-test-user/simple-temple-test-user.go
  src/main/scala/temple/generate/server/go/auth/GoAuthServiceGenerator.scala
  src/main/scala/temple/generate/server/go/auth/GoAuthServiceHookGenerator.scala
  src/main/scala/temple/generate/server/go/common/GoCommonHookGenerator.scala
  src/main/scala/temple/generate/server/go/service/GoServiceGenerator.scala
  src/main/scala/temple/generate/server/go/service/GoServiceHookGenerator.scala
  src/main/scala/temple/generate/server/go/service/main/GoServiceMainCreateHandlerGenerator.scala
  src/main/scala/temple/generate/server/go/service/main/GoServiceMainDeleteHandlerGenerator.scala
  src/main/scala/temple/generate/server/go/service/main/GoServiceMainHandlersGenerator.scala
  src/main/scala/temple/generate/server/go/service/main/GoServiceMainIdentifyHandlerGenerator.scala
  src/main/scala/temple/generate/server/go/service/main/GoServiceMainListHandlerGenerator.scala
  src/main/scala/temple/generate/server/go/service/main/GoServiceMainReadHandlerGenerator.scala
  src/main/scala/temple/generate/server/go/service/main/GoServiceMainUpdateHandlerGenerator.scala
  src/test/resources/generate-server-test/match/hook.go
  src/test/resources/generate-server-test/match/match.go
  src/test/resources/generate-server-test/user/hook.go
  src/test/resources/generate-server-test/user/user.go
  src/test/resources/project-builder-complex/complex-user/complex-user.go
  src/test/resources/project-builder-complex/complex-user/hook.go
Labels: size/L

#357 [Gen] Fix string decapitalisation with the string "ID"
  src/main/scala/temple/utils/StringUtils.scala
  src/test/scala/temple/utils/StringUtilsTest.scala
Labels: size/XS

#359 [project-test] Refactor to extract common logic
  src/main/scala/temple/test/internal/AuthServiceTest.scala
  src/main/scala/temple/test/internal/CRUDServiceTest.scala
  src/main/scala/temple/test/internal/ServiceTest.scala
  src/main/scala/temple/test/internal/ServiceTestUtils.scala
Labels: size/L

#358 [examples] Add shopping example
  examples/shopping.temple
Labels: size/M

#361 [Validator] Block self-references (without @nullable) in foreign keys
  src/main/scala/temple/DSL/semantics/Tarjan.scala
  src/main/scala/temple/DSL/semantics/Validator.scala
  src/test/scala/temple/DSL/semantics/ValidatorTest.scala
Labels: size/S

#364 [Go-Gen] Migrate to new validator library
  src/e2e/resources/simple-temple-expected/auth/auth.go
  src/e2e/resources/simple-temple-expected/booking/booking.go
  src/e2e/resources/simple-temple-expected/simple-temple-test-group/simple-temple-test-group.go
  src/e2e/resources/simple-temple-expected/simple-temple-test-user/simple-temple-test-user.go
  src/main/resources/go/genFiles/auth/main/handlers-metric.go.snippet
  src/main/resources/go/genFiles/auth/main/handlers-no-metric.go.snippet
  src/main/resources/go/genFiles/auth/main/structs.go.snippet
  src/main/scala/temple/generate/server/go/auth/GoAuthServiceMainGenerator.scala
  src/main/scala/temple/generate/server/go/common/GoCommonMainGenerator.scala
  src/main/scala/temple/generate/server/go/service/main/GoServiceMainGenerator.scala
  src/main/scala/temple/generate/server/go/service/main/GoServiceMainHandlersGenerator.scala
  src/main/scala/temple/generate/server/go/service/main/GoServiceMainStructGenerator.scala
  src/test/resources/generate-server-test/auth/auth.go
  src/test/resources/generate-server-test/match/match.go
  src/test/resources/generate-server-test/user/user.go
  src/test/resources/project-builder-complex/auth/auth.go
  src/test/resources/project-builder-complex/complex-user/complex-user.go
  src/test/resources/project-builder-simple/temple-user/temple-user.go
Labels: size/L

#363 [validator] Add additional constraints on foreign keys
  src/main/scala/temple/DSL/semantics/Validator.scala
  src/test/scala/temple/DSL/semantics/ValidatorTest.scala
Labels: size/M

#366 [go-gen] Fix issues with generation of annotated attributes
  src/e2e/resources/attributes-temple-expected/api/attributes.openapi.yaml
  src/e2e/resources/attributes-temple-expected/example-db/init.sql
  src/e2e/resources/attributes-temple-expected/example/Dockerfile
  src/e2e/resources/attributes-temple-expected/example/config.json
  src/e2e/resources/attributes-temple-expected/example/dao/dao.go
  src/e2e/resources/attributes-temple-expected/example/dao/datastore.go
  src/e2e/resources/attributes-temple-expected/example/dao/errors.go
  src/e2e/resources/attributes-temple-expected/example/example.go
  src/e2e/resources/attributes-temple-expected/example/go.mod
  src/e2e/resources/attributes-temple-expected/example/hook.go
  src/e2e/resources/attributes-temple-expected/example/setup.go
  src/e2e/resources/attributes-temple-expected/example/util/util.go
  src/e2e/scala/temple/SimpleE2ETest.scala
  src/it/scala/temple/containers/GolangSpec.scala
  src/it/scala/temple/generate/server/GoGeneratorIntegrationTest.scala
  src/main/scala/temple/ast/AbstractAttribute.scala
  src/main/scala/temple/ast/AbstractServiceBlock.scala
  src/main/scala/temple/builder/DatabaseBuilder.scala
  src/main/scala/temple/builder/ServerBuilder.scala
  src/main/scala/temple/generate/server/AttributesRoot.scala
  src/main/scala/temple/generate/server/go/service/dao/GoServiceDAOFunctionsGenerator.scala
  src/main/scala/temple/generate/server/go/service/dao/GoServiceDAOGenerator.scala
  src/main/scala/temple/generate/server/go/service/dao/GoServiceDAOInputStructsGenerator.scala
  src/main/scala/temple/generate/server/go/service/main/GoServiceMainCreateHandlerGenerator.scala
  src/main/scala/temple/generate/server/go/service/main/GoServiceMainHandlersGenerator.scala
  src/main/scala/temple/generate/server/go/service/main/GoServiceMainUpdateHandlerGenerator.scala
  src/test/scala/temple/generate/target/openapi/OpenAPIGeneratorTest.scala
  src/test/scala/temple/testfiles/attributes.temple
Labels: size/XL

#365 [examples] Add deliveroo.temple
  examples/deliveroo.temple
Labels: size/M

#367 [openapi-gen] Add auth service to OpenAPI gen
  src/e2e/resources/simple-temple-expected/api/simple-temple-test.openapi.yaml
  src/main/scala/temple/builder/OpenAPIBuilder.scala
  src/main/scala/temple/generate/target/openapi/OpenAPIGenerator.scala
  src/main/scala/temple/generate/target/openapi/ast/OpenAPIRoot.scala
  src/test/resources/project-builder-complex/api/sample-complex-project.openapi.yaml
Labels: size/L

#368 [openapi-gen] Fix service name in paths
  src/e2e/resources/simple-temple-expected/api/simple-temple-test.openapi.yaml
  src/main/scala/temple/generate/target/openapi/OpenAPIGenerator.scala
  src/test/resources/project-builder-complex/api/sample-complex-project.openapi.yaml
  src/test/resources/project-builder-simple/api/sample-project.openapi.yaml
Labels: size/M

#369 Auth token openapi
  src/e2e/resources/simple-temple-expected/api/simple-temple-test.openapi.yaml
  src/main/scala/temple/generate/target/openapi/OpenAPIGenerator.scala
  src/main/scala/temple/generate/target/openapi/ast/Handler.scala
  src/main/scala/temple/generate/target/openapi/ast/OpenAPIFile.scala
  src/main/scala/temple/generate/target/openapi/ast/SecurityScheme.scala
  src/test/resources/project-builder-complex/api/sample-complex-project.openapi.yaml
Labels: size/L

#360 [Testing] [Go-gen] Fix illegal shadowing of ID in test
  src/test/scala/temple/builder/BuilderTestData.scala
  src/test/scala/temple/builder/DatabaseBuilderTestData.scala
  src/test/scala/temple/builder/ServerBuilderTest.scala
Labels: size/S

#371 [go-gen] Infer which endpoints to generate
  src/main/scala/temple/builder/DatabaseBuilder.scala
  src/main/scala/temple/builder/ServerBuilder.scala
  src/main/scala/temple/builder/project/ProjectBuilder.scala
  src/test/scala/temple/builder/BuilderTestData.scala
  src/test/scala/temple/builder/DatabaseBuilderTest.scala
  src/test/scala/temple/builder/ServerBuilderTest.scala
Labels: size/L

#362 [testing] [go-gen] Log the output of failed commands before throwing
  src/main/scala/temple/test/ProjectTester.scala
Labels: size/S

#372 [Go-gen] Add struct-root to generate from
  examples/airbnb.temple
  src/it/scala/temple/generate/server/GoGeneratorIntegrationTestData.scala
  src/main/scala/temple/ast/AbstractServiceBlock.scala
  src/main/scala/temple/ast/AttributeBlock.scala
  src/main/scala/temple/builder/ServerBuilder.scala
  src/main/scala/temple/generate/server/AttributesRoot.scala
  src/main/scala/temple/generate/server/ParentAttribute.scala
  src/test/scala/temple/builder/ServerBuilderTest.scala
  src/test/scala/temple/generate/server/go/GoServiceGeneratorTestData.scala
Labels: size/L
