Repository TempleEight/temple, pull requests merged in 2020-02, with the labels that each got.

#40 [Travis] Combine test and code cov step
  .travis.yml
Labels: size/XS

#42 [Code-Formatting] Refactor `SQLTerm` to be generic
  src/main/scala/temple/generate/database/PostgresGenerator.scala
  src/main/scala/temple/generate/database/SQLTerm.scala
  src/main/scala/temple/generate/utils/CodeTerm.scala
Labels: size/L

#43 Test naming
  src/it/scala/temple/generate/database/PostgresGeneratorIntegrationTest.scala
  src/test/scala/temple/DSL/parser/DSLParserTest.scala
  src/test/scala/temple/DSL/semantics/SemanticAnalyserTest.scala
  src/test/scala/temple/TempleConfigTest.scala
  src/test/scala/temple/collection/enumeration/EnumTest.scala
  src/test/scala/temple/generate/database/PostgresGeneratorTest.scala
  src/test/scala/temple/utils/FileUtilsTest.scala
  src/test/scala/temple/utils/MapUtilsTest.scala
  src/test/scala/temple/utils/SeqUtilsTest.scala
  src/test/scala/temple/utils/StringUtilsTest.scala
Labels: size/L

#44 [Semantics] Allow metadata to be queried by type, with defaults
  src/main/scala/temple/DSL/semantics/Analyser.scala
  src/main/scala/temple/DSL/semantics/ProjectBlock.scala
  src/main/scala/temple/DSL/semantics/ServiceBlock.scala
  src/main/scala/temple/DSL/semantics/TargetBlock.scala
  src/main/scala/temple/DSL/semantics/TempleBlock.scala
  src/main/scala/temple/DSL/semantics/Templefile.scala
  src/test/scala/temple/DSL/semantics/SemanticAnalyserTest.scala
  src/test/scala/temple/DSL/semantics/TempleBlockTest.scala
Labels: size/M

#41 [Docker-Gen] Basic Dockerfile generation
  build.sbt
  src/main/scala/temple/generate/docker/DockerfileGenerator.scala
  src/main/scala/temple/generate/docker/ast/DockerfileRoot.scala
  src/main/scala/temple/generate/docker/ast/Statement.scala
  src/main/scala/temple/generate/utils/CodeTerm.scala
  src/test/scala/temple/generate/docker/DockerfileGeneratorTest.scala
  src/test/scala/temple/generate/docker/UnitTestData.scala
Labels: size/L

#45 [test][sql-gen] Add integration test for table constraints
  src/it/scala/temple/containers/PostgresSpec.scala
  src/it/scala/temple/generate/database/PostgresGeneratorIntegrationTest.scala
  src/it/scala/temple/generate/database/TestData.scala
Labels: size/L

#46 [Semantics] Make all attribute type parameters optional
  src/main/scala/temple/DSL/semantics/Analyser.scala
  src/main/scala/temple/DSL/semantics/AttributeType.scala
Labels: size/S

#47 [Docker-Gen] Implement RUN, CMD and EXPOSE commands
  src/main/scala/temple/generate/docker/DockerfileGenerator.scala
  src/main/scala/temple/generate/docker/ast/Statement.scala
  src/test/scala/temple/generate/docker/DockerfileGeneratorTest.scala
  src/test/scala/temple/generate/docker/UnitTestData.scala
  src/test/scala/temple/generate/docker/ast/StatementTest.scala
Labels: size/M

#48 [SQL-Gen] Add support for short, long and double precision types
  src/it/scala/temple/containers/PostgresSpec.scala
  src/it/scala/temple/generate/database/PostgresGeneratorIntegrationTest.scala
  src/it/scala/temple/generate/database/PreparedVariable.scala
  src/it/scala/temple/generate/database/TestData.scala
  src/main/scala/temple/generate/database/PostgresGenerator.scala
  src/main/scala/temple/generate/database/ast/ColType.scala
  src/test/scala/temple/generate/database/IntegrationTestData.scala
Labels: size/L

#49 [SQL-Gen] Add support for VARCHAR types
  src/it/scala/temple/generate/database/PostgresGeneratorIntegrationTest.scala
  src/it/scala/temple/generate/database/TestData.scala
  src/main/scala/temple/generate/database/PostgresGenerator.scala
  src/main/scala/temple/generate/database/ast/ColType.scala
  src/test/scala/temple/generate/database/IntegrationTestData.scala
Labels: size/M

#50 [Docker-Gen] Implement more Dockerfile Commands
  src/main/scala/temple/generate/docker/DockerfileGenerator.scala
  src/main/scala/temple/generate/docker/ast/Statement.scala
  src/test/scala/temple/generate/docker/UnitTestData.scala
Labels: size/M

#51 [SQL-Gen] Map from semantic types into database creation types
  src/main/scala/temple/builder/DatabaseBuilder.scala
  src/main/scala/temple/generate/database/ast/ColType.scala
  src/test/scala/temple/builder/DatabaseBuilderTest.scala
  src/test/scala/temple/builder/DatabaseBuilderTestData.scala
Labels: size/L

#52 [SQL-gen] Refactor flattening of services into tables
  src/main/scala/temple/DSL/semantics/ServiceBlock.scala
  src/main/scala/temple/builder/DatabaseBuilder.scala
  src/test/scala/temple/builder/DatabaseBuilderTestData.scala
Labels: size/S

#54 [builder] Project Builder
  src/main/scala/temple/builder/project/Project.scala
  src/main/scala/temple/builder/project/ProjectBuilder.scala
  src/test/scala/temple/builder/project/ProjectBuilderTest.scala
  src/test/scala/temple/builder/project/ProjectBuilderTestData.scala
Labels: size/L

#55 [SQL-gen] Remove NULL constraint
  src/main/scala/temple/DSL/semantics/Annotation.scala
  src/main/scala/temple/generate/database/PostgresGenerator.scala
  src/test/scala/temple/generate/database/PostgresGeneratorTest.scala
  src/test/scala/temple/generate/database/PostgresGeneratorTestData.scala
Labels: size/S

#57 [builder] Perform file IO with templefiles
  src/main/scala/temple/Main.scala
  src/main/scala/temple/builder/project/FileType.scala
  src/main/scala/temple/builder/project/Project.scala
  src/main/scala/temple/builder/project/ProjectBuilder.scala
  src/test/scala/temple/builder/project/ProjectBuilderTest.scala
  src/test/scala/temple/builder/project/ProjectBuilderTestData.scala
Labels: size/M

#56 [SQL-Gen] Add nullable annotation
  src/main/scala/temple/DSL/semantics/Analyser.scala
  src/main/scala/temple/builder/DatabaseBuilder.scala
  src/test/scala/temple/DSL/parser/DSLParserTest.scala
  src/test/scala/temple/DSL/semantics/SemanticAnalyserTest.scala
  src/test/scala/temple/builder/DatabaseBuilderTestData.scala
  src/test/scala/temple/builder/project/ProjectBuilderTestData.scala
  src/test/scala/temple/testfiles/simple.temple
Labels: size/L

#58 [SQL-gen] Remove unused Null case class
  src/main/scala/temple/generate/database/ast/ColumnConstraint.scala
Labels: size/XS

#60 [AST] Do not require semicolons before close braces
  src/main/scala/temple/DSL/parser/DSLParser.scala
Labels: size/XS

#62 [AST] Improve the test failure messages for parse failures
  src/test/scala/temple/DSL/parser/DSLParserTest.scala
Labels: size/S

#63 [Semantics] Add name of foreign table to foreign key attribute type
  src/main/scala/temple/DSL/semantics/AttributeType.scala
  src/main/scala/temple/builder/DatabaseBuilder.scala
Labels: size/M

#61 [test] Add initial end to end test
  .travis.yml
  build.sbt
  src/e2e/scala/temple/SimpleEndToEndTest.scala
  src/e2e/scala/temple/SimpleEndToEndTestData.scala
  src/e2e/scala/temple/testfiles/simple.temple
  src/main/scala/temple/Application.scala
  src/main/scala/temple/Main.scala
Labels: size/L

#53 [AST] Distinguish structs/services from types
  src/main/scala/temple/DSL/parser/DSLParser.scala
  src/main/scala/temple/DSL/semantics/Analyser.scala
  src/main/scala/temple/DSL/syntax/AttributeType.scala
  src/test/scala/temple/DSL/parser/DSLParserTest.scala
  src/test/scala/temple/DSL/semantics/SemanticAnalyserTest.scala
  src/test/scala/temple/DSL/semantics/TempleBlockTest.scala
  src/test/scala/temple/testfiles/simple.temple
Labels: size/L

#64 [Infra] Travis stages in parallel
  .travis.yml
Labels: size/XS

#59 [Infra] Distribution with CD
  .travis.yml
  DEPLOYMENT
  build.sbt
  project/plugins.sbt
Labels: size/M

#65 [builder] Remove filetype and append with filename
  src/main/scala/temple/Application.scala
  src/main/scala/temple/builder/project/FileType.scala
  src/main/scala/temple/builder/project/Project.scala
  src/main/scala/temple/builder/project/ProjectBuilder.scala
  src/test/scala/temple/builder/project/ProjectBuilderTest.scala
Labels: size/S

#66 [Semantics] Distinguish language config between services and targets
  src/main/scala/temple/DSL/semantics/Analyser.scala
  src/main/scala/temple/DSL/semantics/Metadata.scala
  src/test/scala/temple/DSL/semantics/TempleBlockTest.scala
Labels: size/M

#67 [Infra] Skip assembling in preparation for deployment
  .travis.yml
Labels: size/XS

#69 [Semantics] Remove unused failHandler redirect for semantic parsing
  src/main/scala/temple/DSL/semantics/ErrorHandling.scala
Labels: size/XS

#68 [Semantics] Remove unused String argument type in the DSL
  src/main/scala/temple/DSL/semantics/ArgType.scala
Labels: size/XS

#70 [DSL] Support the Enumerate metadata item
  src/main/scala/temple/DSL/parser/DSLParser.scala
  src/main/scala/temple/DSL/semantics/Analyser.scala
  src/main/scala/temple/DSL/semantics/Metadata.scala
  src/main/scala/temple/DSL/semantics/MetadataParser.scala
  src/main/scala/temple/DSL/syntax/Entry.scala
  src/main/scala/temple/generate/utils/CodeTerm.scala
  src/test/scala/temple/DSL/parser/DSLParserTest.scala
  src/test/scala/temple/DSL/semantics/SemanticAnalyserTest.scala
  src/test/scala/temple/testfiles/simple.temple
Labels: size/M

#71 [DSL] Add support for comments in the DSL
  src/main/scala/temple/DSL/parser/DSLParser.scala
  src/test/scala/temple/testfiles/simple.temple
Labels: size/S

#73 [deployment] Fix typos in markdown
  DEPLOYMENT
Labels: size/XS

#74 Release/0.1.0
  build.sbt
  project/build.properties
  project/plugins.sbt
  src/main/scala/temple/DSL/semantics/Analyser.scala
  src/main/scala/temple/DSL/semantics/ErrorHandling.scala
  src/main/scala/temple/builder/project/ProjectBuilder.scala
  src/main/scala/temple/utils/FileUtils.scala
  src/test/scala/temple/builder/project/ProjectBuilderTestData.scala
Labels: size/M

#72 Dockerfile integration tests
  build.sbt
  docker/deploy.sh
  docker/hadolint.Dockerfile
  src/it/scala/temple/containers/DockerHadolintService.scala
  src/it/scala/temple/containers/HadolintSpec.scala
  src/it/scala/temple/generate/docker/DockerGeneratorIntegrationTest.scala
Labels: size/L

#79 Allow metadata in structs
  src/e2e/scala/temple/DSL/ParserE2ETest.scala
  src/e2e/scala/temple/SimpleE2ETest.scala
  src/e2e/scala/temple/SimpleE2ETestData.scala
  src/e2e/scala/temple/testfiles/simple.temple
  src/main/scala/temple/DSL/semantics/Analyser.scala
  src/main/scala/temple/DSL/semantics/Metadata.scala
  src/main/scala/temple/DSL/semantics/ProjectBlock.scala
  src/main/scala/temple/DSL/semantics/StructBlock.scala
  src/main/scala/temple/DSL/semantics/TargetBlock.scala
  src/test/scala/temple/DSL/parser/DSLParserMatchers.scala
  src/test/scala/temple/DSL/parser/DSLParserTest.scala
  src/test/scala/temple/DSL/semantics/SemanticAnalyserTest.scala
  src/test/scala/temple/builder/project/ProjectBuilderTestData.scala
Labels: size/L

#81 [Semantics] Boost code coverage of semantic parser
  src/test/scala/temple/DSL/semantics/SemanticAnalyserTest.scala
  src/test/scala/temple/utils/FileUtilsTest.scala
  src/test/scala/temple/utils/SeqUtilsTest.scala
Labels: size/L

#80 [test][docker] Add Dockerfile test
  src/it/scala/temple/generate/docker/DockerGeneratorIntegrationTest.scala
Labels: size/S

#83 Table naming
  src/e2e/scala/temple/DSL/ParserE2ETest.scala
  src/e2e/scala/temple/SimpleE2ETest.scala
  src/e2e/scala/temple/SimpleE2ETestData.scala
  src/it/scala/temple/generate/database/PostgresGeneratorIntegrationTest.scala
  src/it/scala/temple/generate/database/TestData.scala
  src/main/scala/temple/builder/DatabaseBuilder.scala
  src/main/scala/temple/utils/StringUtils.scala
  src/test/scala/temple/DSL/parser/DSLParserTest.scala
  src/test/scala/temple/builder/DatabaseBuilderTest.scala
  src/test/scala/temple/builder/DatabaseBuilderTestData.scala
  src/test/scala/temple/builder/project/ProjectBuilderTest.scala
  src/test/scala/temple/builder/project/ProjectBuilderTestData.scala
  src/test/scala/temple/testfiles/simple.temple
  src/test/scala/temple/utils/StringUtilsTest.scala
Labels: size/L

#84 [builder] Rename project argument to files and use global configuration
  src/main/scala/temple/Application.scala
  src/main/scala/temple/builder/project/Project.scala
  src/main/scala/temple/builder/project/ProjectBuilder.scala
  src/main/scala/temple/builder/project/ProjectConfig.scala
  src/test/scala/temple/builder/project/ProjectBuilderTest.scala
Labels: size/S

#82 [test] Add tests for parsing keyword arguments in any order
  src/test/scala/temple/DSL/semantics/SemanticAnalyserTest.scala
Labels: size/M

#85 Builder test data
  src/test/scala/temple/builder/BuilderTestData.scala
  src/test/scala/temple/builder/DatabaseBuilderTest.scala
  src/test/scala/temple/builder/DatabaseBuilderTestData.scala
Labels: size/M

#86 [builder][docker] Build dockerfile from language
  src/main/scala/temple/DSL/semantics/Metadata.scala
  src/main/scala/temple/builder/DockerfileBuilder.scala
  src/main/scala/temple/builder/project/ProjectConfig.scala
  src/test/scala/temple/DSL/semantics/TempleBlockTest.scala
  src/test/scala/temple/builder/DockerfileBuilderTest.scala
  src/test/scala/temple/builder/DockerfileBuilderTestData.scala
Labels: size/L

#88 [CLI] Print correct version number
  build.sbt
  project/plugins.sbt
  src/main/scala/temple/TempleConfig.scala
Labels: size/XS

#91 [test][golang] Add integration test support for Golang
  docker/deploy.sh
  docker/hadolint.Dockerfile
  docker/shell2http.Dockerfile
  src/it/scala/temple/containers/DockerHadolintService.scala
  src/it/scala/temple/containers/DockerShell2HttpService.scala
  src/it/scala/temple/containers/GolangSpec.scala
  src/it/scala/temple/containers/HadolintSpec.scala
  src/it/scala/temple/generate/language/service/GoGeneratorIntegrationTest.scala
Labels: size/L

#92 [test] Use consistent newlines between behavior and tests
  src/e2e/scala/temple/SimpleE2ETest.scala
  src/it/scala/temple/generate/database/PostgresGeneratorIntegrationTest.scala
  src/it/scala/temple/generate/docker/DockerGeneratorIntegrationTest.scala
  src/it/scala/temple/generate/language/service/GoGeneratorIntegrationTest.scala
  src/test/scala/temple/TempleConfigTest.scala
  src/test/scala/temple/builder/DatabaseBuilderTest.scala
  src/test/scala/temple/builder/DockerfileBuilderTest.scala
  src/test/scala/temple/builder/project/ProjectBuilderTest.scala
  src/test/scala/temple/utils/StringUtilsTest.scala
Labels: size/S

#93 [go-gen] Generalise codeparens
  src/main/scala/temple/DSL/syntax/Entry.scala
  src/main/scala/temple/generate/database/PostgresGenerator.scala
  src/main/scala/temple/generate/utils/CodeTerm.scala
Labels: size/M

#89 [builder][docker] Output Dockerfile for each service, add integration and E2E tests
  src/e2e/scala/temple/SimpleE2ETest.scala
  src/e2e/scala/temple/SimpleE2ETestData.scala
  src/it/scala/temple/generate/docker/DockerGeneratorIntegrationTest.scala
  src/it/scala/temple/generate/docker/DockerGeneratorIntegrationTestData.scala
  src/main/scala/temple/builder/project/ProjectBuilder.scala
  src/test/scala/temple/builder/project/ProjectBuilderTest.scala
  src/test/scala/temple/builder/project/ProjectBuilderTestData.scala
Labels: size/L

#94 [go-gen] Simplify CodeWrap
  src/main/scala/temple/DSL/syntax/Entry.scala
  src/main/scala/temple/generate/database/PostgresGenerator.scala
  src/main/scala/temple/generate/utils/CodeTerm.scala
  src/main/scala/temple/utils/StringUtils.scala
  src/test/scala/temple/utils/StringUtilsTest.scala
Labels: size/M

#95 [go-gen] Enquote
  src/main/scala/temple/generate/language/service/go/GoServiceGenerator.scala
  src/main/scala/temple/generate/utils/CodeTerm.scala
  src/main/scala/temple/utils/StringUtils.scala
Labels: size/M

#90 [go-gen] Add package and import generation
  src/main/scala/temple/builder/project/Project.scala
  src/main/scala/temple/builder/project/ProjectBuilder.scala
  src/main/scala/temple/generate/language/service/ServiceGenerator.scala
  src/main/scala/temple/generate/language/service/adt/ServiceRoot.scala
  src/main/scala/temple/generate/language/service/go/GoServiceGenerator.scala
  src/main/scala/temple/generate/utils/CodeTerm.scala
  src/main/scala/temple/utils/FileUtils.scala
  src/main/scala/temple/utils/StringUtils.scala
  src/test/scala/temple/builder/project/ProjectBuilderTest.scala
  src/test/scala/temple/generate/language/service/go/GoServiceGeneratorTest.scala
  src/test/scala/temple/generate/language/service/go/GoServiceGeneratorTestData.scala
  src/test/scala/temple/generate/language/service/go/testfiles/match.go
  src/test/scala/temple/generate/language/service/go/testfiles/user.go
Labels: size/L

#96 [go-gen] Add main generation
  src/main/scala/temple/generate/language/service/adt/Endpoint.scala
  src/main/scala/temple/generate/language/service/adt/ServiceRoot.scala
  src/main/scala/temple/generate/language/service/go/GoServiceGenerator.scala
  src/test/scala/temple/generate/language/service/go/GoServiceGeneratorTestData.scala
  src/test/scala/temple/generate/language/service/go/testfiles/match.go
  src/test/scala/temple/generate/language/service/go/testfiles/user.go
Labels: size/L

#97 [go-gen] Add global, empty handler, jsonMiddleware and errors.go generation
  src/main/scala/temple/generate/language/service/adt/Endpoint.scala
  src/main/scala/temple/generate/language/service/go/GoServiceGenerator.scala
  src/main/scala/temple/generate/language/service/go/genFiles/JsonMiddleware.go
  src/test/scala/temple/generate/language/service/go/GoServiceGeneratorTestData.scala
  src/test/scala/temple/generate/language/service/go/testfiles/match/dao/errors.go
  src/test/scala/temple/generate/language/service/go/testfiles/match/match.go
  src/test/scala/temple/generate/language/service/go/testfiles/user/dao/errors.go
  src/test/scala/temple/generate/language/service/go/testfiles/user/user.go
Labels: size/L

#100 [españolQue] Fix code coverage
  src/test/scala/temple/utils/StringUtilsTest.scala
Labels: size/XS

#101 [go-gen] Fix utils->util, and match gofmt output
  src/main/scala/temple/generate/language/service/go/GoServiceGenerator.scala
  src/test/scala/temple/generate/language/service/go/testfiles/match/comm/handler.go
  src/test/scala/temple/generate/language/service/go/testfiles/match/match.go
  src/test/scala/temple/generate/language/service/go/testfiles/user/user.go
Labels: size/S
