Repository TempleEight/temple, pull requests merged in 2020-03, with the labels that each got.

#102 [it] Allow multiple files for Golang integration tests
  docker/configure_go.py
  docker/deploy.sh
  docker/shell2http.Dockerfile
  src/it/scala/temple/containers/DockerShell2HttpService.scala
  src/it/scala/temple/containers/GolangSpec.scala
  src/it/scala/temple/generate/language/service/GoGeneratorIntegrationTest.scala
Labels: size/M

#98 [code-gen] Generate line-separated code
  src/main/scala/temple/generate/language/service/go/GoServiceGenerator.scala
  src/main/scala/temple/generate/utils/CodeTerm.scala
Labels: size/M

#103 [it][test] Run go mod tidy prior to building the project
  docker/shell2http.Dockerfile
Labels: size/XS

#104 Bump docker image 1.2
  docker/deploy.sh
  src/it/scala/temple/containers/DockerShell2HttpService.scala
Labels: size/XS

#105 [go-gen] Add integration tests for compiling generated Go
  src/it/scala/temple/generate/language/service/GoGeneratorIntegrationTest.scala
  src/it/scala/temple/generate/language/service/GoGeneratorIntegrationTestData.scala
  src/main/scala/temple/generate/language/service/go/GoServiceGenerator.scala
  src/test/scala/temple/generate/language/service/go/GoServiceGeneratorTestData.scala
  src/test/scala/temple/generate/language/service/go/testfiles/match/comm/handler.go
  src/test/scala/temple/generate/language/service/go/testfiles/match/go.mod
  src/test/scala/temple/generate/language/service/go/testfiles/match/match.go
  src/test/scala/temple/generate/language/service/go/testfiles/user/go.mod
  src/test/scala/temple/generate/language/service/go/testfiles/user/user.go
Labels: size/L

#109 [meh] Move file type to own file
  src/it/scala/temple/containers/GolangSpec.scala
  src/it/scala/temple/generate/service/GoGeneratorIntegrationTest.scala
  src/main/scala/temple/builder/project/Project.scala
  src/main/scala/temple/builder/project/ProjectBuilder.scala
  src/main/scala/temple/generate/FileSystem.scala
  src/main/scala/temple/generate/service/ServiceGenerator.scala
  src/main/scala/temple/generate/service/go/GoServiceGenerator.scala
  src/main/scala/temple/utils/FileUtils.scala
  src/test/scala/temple/builder/project/ProjectBuilderTest.scala
  src/test/scala/temple/generate/service/go/GoServiceGeneratorTestData.scala
Labels: size/M

#110 [go-gen] Refactor go code generation by package
  src/main/scala/temple/generate/service/ServiceGenerator.scala
  src/main/scala/temple/generate/service/go/GoServiceCommGenerator.scala
  src/main/scala/temple/generate/service/go/GoServiceDaoGenerator.scala
  src/main/scala/temple/generate/service/go/GoServiceGenerator.scala
  src/main/scala/temple/generate/service/go/GoServiceMainGenerator.scala
  src/main/scala/temple/generate/service/go/GoServiceUtilGenerator.scala
Labels: size/L

#111 Openapi gen
  .gitignore
  build.sbt
  src/main/scala/temple/generate/target/openapi/JsonEncodable.scala
  src/main/scala/temple/generate/target/openapi/OpenAPIGenerator.scala
  src/main/scala/temple/generate/target/openapi/OpenAPIType.scala
  src/main/scala/temple/generate/target/openapi/Response.scala
  src/test/scala/temple/generate/target/openapi/OpenAPIGeneratorTest.scala
Labels: size/L

#112 [openapi-gen] Refactor JsonEncodable
  src/main/scala/temple/generate/JsonEncodable.scala
  src/main/scala/temple/generate/target/openapi/JsonEncodable.scala
  src/main/scala/temple/generate/target/openapi/OpenAPIGenerator.scala
  src/main/scala/temple/generate/target/openapi/OpenAPIType.scala
  src/main/scala/temple/generate/target/openapi/Response.scala
Labels: size/M

#113 [K8s-Gen] Generate kube yaml file headers for all services
  src/main/scala/temple/generate/kube/GenType.scala
  src/main/scala/temple/generate/kube/KubernetesGenerator.scala
  src/main/scala/temple/generate/kube/ast/OrchestrationType.scala
  src/main/scala/temple/generate/kube/ast/gen/KubeType.scala
  src/test/scala/temple/generate/kube/KubernetesGeneratorTest.scala
  src/test/scala/temple/generate/kube/UnitTestData.scala
Labels: size/L

#116 [openapi-gen] Add data structures for full OpenAPI generation
  src/main/scala/temple/generate/target/openapi/HTTPVerb.scala
  src/main/scala/temple/generate/target/openapi/Literal.scala
  src/main/scala/temple/generate/target/openapi/MediaTypeObject.scala
  src/main/scala/temple/generate/target/openapi/OpenAPIFile.scala
  src/main/scala/temple/generate/target/openapi/OpenAPIGenerator.scala
  src/main/scala/temple/generate/target/openapi/Path.scala
  src/main/scala/temple/generate/target/openapi/RequestBody.scala
  src/main/scala/temple/generate/target/openapi/Response.scala
Labels: size/L

#114 [K8s-Gen] Generate correct Service Deployment Yaml
  src/main/scala/temple/generate/kube/KubernetesGenerator.scala
  src/main/scala/temple/generate/kube/ast/OrchestrationType.scala
  src/main/scala/temple/generate/kube/ast/gen/KubeType.scala
  src/main/scala/temple/generate/kube/ast/gen/Spec.scala
  src/test/resources/kube/user-deployment.yaml
  src/test/resources/kube/user-service.yaml
  src/test/scala/temple/generate/kube/KubernetesGeneratorTest.scala
  src/test/scala/temple/generate/kube/UnitTestData.scala
Labels: size/M

#115 [api] Add FlagMapView, for use with OpenAPI generation
  src/main/scala/temple/collection/FlagMapView.scala
  src/test/scala/temple/collection/FlagMapViewTest.scala
Labels: size/L

#118 [OpenAPI-gen] Finalise datastructures in preparation for generation
  src/main/scala/temple/generate/target/openapi/OpenAPIFile.scala
  src/main/scala/temple/generate/target/openapi/OpenAPIType.scala
  src/main/scala/temple/generate/target/openapi/Service.scala
Labels: size/M

#119 [openAPI-gen] Generate the first endpoint in OpenAPI format
  src/main/scala/temple/generate/target/openapi/BodyLiteral.scala
  src/main/scala/temple/generate/target/openapi/OpenAPIGenerator.scala
  src/test/scala/temple/generate/target/openapi/OpenAPIGeneratorTest.scala
Labels: size/L

#120 [OpenAPI-gen] Add parent trait for JsonEncodable, so non-objects can be encoded
  src/main/scala/temple/generate/JsonEncodable.scala
  src/main/scala/temple/generate/kube/ast/gen/Spec.scala
  src/main/scala/temple/generate/target/openapi/MediaTypeObject.scala
  src/main/scala/temple/generate/target/openapi/OpenAPIFile.scala
  src/main/scala/temple/generate/target/openapi/OpenAPIType.scala
  src/main/scala/temple/generate/target/openapi/RequestBody.scala
  src/main/scala/temple/generate/target/openapi/Response.scala
Labels: size/M

#121 Json encodable arrows
  src/main/scala/temple/generate/JsonEncodable.scala
  src/main/scala/temple/generate/kube/ast/gen/KubeType.scala
  src/main/scala/temple/generate/kube/ast/gen/Spec.scala
  src/main/scala/temple/generate/target/openapi/BodyLiteral.scala
  src/main/scala/temple/generate/target/openapi/MediaTypeObject.scala
  src/main/scala/temple/generate/target/openapi/OpenAPIFile.scala
  src/main/scala/temple/generate/target/openapi/OpenAPIType.scala
  src/main/scala/temple/generate/target/openapi/RequestBody.scala
  src/main/scala/temple/generate/target/openapi/Response.scala
Labels: size/M

#117 [openAPI-gen] Generate Create endpoints in OpenAPI format
  src/main/scala/temple/generate/target/openapi/OpenAPIGenerator.scala
  src/test/scala/temple/generate/target/openapi/OpenAPIGeneratorTest.scala
Labels: size/L

#123 [it][openapi-gen] Add base integration test framework for OpenAPI
  docker/deploy.sh
  docker/shell2http.Dockerfile
  src/it/scala/temple/containers/DockerShell2HttpService.scala
  src/it/scala/temple/containers/SwaggerSpec.scala
  src/it/scala/temple/generate/target/openapi/OpenAPIGeneratorIntegrationTest.scala
Labels: size/M

#122 [K8s-Gen] Generate Database Deployment Scripts
  src/main/scala/temple/generate/kube/KubernetesGenerator.scala
  src/main/scala/temple/generate/kube/ast/OrchestrationType.scala
  src/main/scala/temple/generate/kube/ast/gen/KubeType.scala
  src/main/scala/temple/generate/kube/ast/gen/LifecycleCommand.scala
  src/main/scala/temple/generate/kube/ast/gen/PlacementStrategy.scala
  src/main/scala/temple/generate/kube/ast/gen/RestartPolicy.scala
  src/main/scala/temple/generate/kube/ast/gen/Spec.scala
  src/test/resources/kube/user-db-deployment.yaml
  src/test/scala/temple/generate/kube/KubernetesGeneratorTest.scala
  src/test/scala/temple/generate/kube/UnitTestData.scala
Labels: size/L

#126 [go-gen] Setup auth generation and generate auth imports
  src/main/scala/temple/generate/service/AuthServiceGenerator.scala
  src/main/scala/temple/generate/service/AuthServiceRoot.scala
  src/main/scala/temple/generate/service/go/GoCommonGenerator.scala
  src/main/scala/temple/generate/service/go/GoServiceGenerator.scala
  src/main/scala/temple/generate/service/go/auth/GoAuthServiceGenerator.scala
  src/main/scala/temple/generate/service/go/auth/GoAuthServiceMainGenerator.scala
  src/test/scala/temple/generate/service/go/GoAuthServiceGeneratorTest.scala
  src/test/scala/temple/generate/service/go/GoAuthServiceGeneratorTestData.scala
  src/test/scala/temple/generate/service/go/testfiles/auth/auth.go
  src/test/scala/temple/generate/service/go/testfiles/auth/go.mod
Labels: size/L

#125 [OpenAPI-gen] Add Read generator
  src/main/scala/temple/generate/target/openapi/Handler.scala
  src/main/scala/temple/generate/target/openapi/OpenAPIFile.scala
  src/main/scala/temple/generate/target/openapi/OpenAPIGenerator.scala
  src/main/scala/temple/generate/target/openapi/Parameter.scala
  src/main/scala/temple/generate/target/openapi/Path.scala
  src/test/scala/temple/generate/target/openapi/OpenAPIGeneratorTest.scala
Labels: size/L

#124 [K8s-Gen] DB-Service and Storage Generation
  src/main/scala/temple/generate/kube/KubernetesGenerator.scala
  src/main/scala/temple/generate/kube/ast/OrchestrationType.scala
  src/main/scala/temple/generate/kube/ast/gen/LifecycleCommand.scala
  src/main/scala/temple/generate/kube/ast/gen/PlacementStrategy.scala
  src/main/scala/temple/generate/kube/ast/gen/RestartPolicy.scala
  src/main/scala/temple/generate/kube/ast/gen/Spec.scala
  src/main/scala/temple/generate/kube/ast/gen/volume/AccessMode.scala
  src/main/scala/temple/generate/kube/ast/gen/volume/ReclaimPolicy.scala
  src/main/scala/temple/generate/kube/ast/gen/volume/StorageClass.scala
  src/test/resources/kube/user-db-service.yaml
  src/test/resources/kube/user-db-storage.yaml
  src/test/scala/temple/generate/kube/KubernetesGeneratorTest.scala
  src/test/scala/temple/generate/kube/UnitTestData.scala
Labels: size/L

#128 [go-gen] Generate auth.go aside from main and handlers
  src/main/resources/go/genFiles/auth/create_token.go
  src/main/resources/go/genFiles/auth/handlers.go
  src/main/resources/go/genFiles/auth/router.go
  src/main/resources/go/genFiles/auth/structs.go
  src/main/scala/temple/generate/service/go/GoCommonGenerator.scala
  src/main/scala/temple/generate/service/go/GoServiceGenerator.scala
  src/main/scala/temple/generate/service/go/GoServiceMainGenerator.scala
  src/main/scala/temple/generate/service/go/auth/GoAuthServiceGenerator.scala
  src/main/scala/temple/generate/service/go/auth/GoAuthServiceMainGenerator.scala
  src/test/scala/temple/generate/service/go/testfiles/auth/auth.go
Labels: size/L

#129 [K8s-Gen] Kong Files
  src/main/resources/kube/kong/kong-db-deployment.yaml
  src/main/resources/kube/kong/kong-db-service.yaml
  src/main/resources/kube/kong/kong-deployment.yaml
  src/main/resources/kube/kong/kong-migration-job.yaml
  src/main/resources/kube/kong/kong-service.yaml
  src/main/scala/temple/generate/kube/KubernetesGenerator.scala
  src/test/scala/temple/generate/kube/KubernetesGeneratorTest.scala
Labels: size/L

#127 [Scalafmt] Align based on JsonEncodable arrows
  .scalafmt.conf
  src/main/scala/temple/generate/kube/ast/gen/KubeType.scala
  src/main/scala/temple/generate/kube/ast/gen/Spec.scala
  src/main/scala/temple/generate/service/go/GoCommonGenerator.scala
  src/main/scala/temple/generate/service/go/GoServiceGenerator.scala
  src/main/scala/temple/generate/service/go/GoServiceMainGenerator.scala
  src/main/scala/temple/generate/service/go/auth/GoAuthServiceGenerator.scala
  src/main/scala/temple/generate/target/openapi/BodyLiteral.scala
  src/main/scala/temple/generate/target/openapi/Handler.scala
  src/main/scala/temple/generate/target/openapi/OpenAPIFile.scala
  src/main/scala/temple/generate/target/openapi/Parameter.scala
Labels: size/M

#130 [go-gen] Generate handler.go for Auth service aside from Init function
  src/main/resources/go/genFiles/auth/comm/create_jwt_credential.go
  src/main/resources/go/genFiles/auth/comm/structs.go
  src/main/scala/temple/generate/service/go/GoCommonGenerator.scala
  src/main/scala/temple/generate/service/go/GoServiceCommGenerator.scala
  src/main/scala/temple/generate/service/go/GoServiceGenerator.scala
  src/main/scala/temple/generate/service/go/auth/GoAuthServiceCommGenerator.scala
  src/main/scala/temple/generate/service/go/auth/GoAuthServiceGenerator.scala
  src/test/scala/temple/generate/service/go/GoAuthServiceGeneratorTestData.scala
  src/test/scala/temple/generate/service/go/testfiles/auth/comm/handler.go
Labels: size/L

#131 [k8s-gen] Generate Kong Config
  src/main/scala/temple/generate/kube/KongConfigGenerator.scala
  src/main/scala/temple/generate/kube/KubernetesGenerator.scala
  src/main/scala/temple/generate/kube/ast/OrchestrationType.scala
  src/main/scala/temple/generate/utils/CodeTerm.scala
  src/test/resources/kong/configure-kong.sh
  src/test/scala/temple/generate/kube/KongConfigGeneratorTest.scala
  src/test/scala/temple/generate/kube/KubernetesGeneratorTest.scala
  src/test/scala/temple/generate/kube/UnitTestData.scala
Labels: size/L

#133 [OpenAPI-gen] Rename Endpoint to CRUD/Operation
  src/it/scala/temple/generate/service/GoGeneratorIntegrationTestData.scala
  src/main/scala/temple/generate/CRUD.scala
  src/main/scala/temple/generate/Endpoint.scala
  src/main/scala/temple/generate/service/ServiceGenerator.scala
  src/main/scala/temple/generate/service/ServiceRoot.scala
  src/main/scala/temple/generate/service/go/GoServiceGenerator.scala
  src/main/scala/temple/generate/service/go/GoServiceMainGenerator.scala
  src/main/scala/temple/generate/target/openapi/OpenAPIGenerator.scala
  src/main/scala/temple/generate/target/openapi/Service.scala
  src/test/scala/temple/generate/service/go/GoServiceGeneratorTestData.scala
  src/test/scala/temple/generate/target/openapi/OpenAPIGeneratorTest.scala
Labels: size/L

#136 [OpenAPI-gen] Move OpenAPI AST to its own folder
  src/main/scala/temple/generate/target/openapi/OpenAPIGenerator.scala
  src/main/scala/temple/generate/target/openapi/ast/BodyLiteral.scala
  src/main/scala/temple/generate/target/openapi/ast/HTTPVerb.scala
  src/main/scala/temple/generate/target/openapi/ast/Handler.scala
  src/main/scala/temple/generate/target/openapi/ast/MediaTypeObject.scala
  src/main/scala/temple/generate/target/openapi/ast/OpenAPIFile.scala
  src/main/scala/temple/generate/target/openapi/ast/OpenAPIType.scala
  src/main/scala/temple/generate/target/openapi/ast/Parameter.scala
  src/main/scala/temple/generate/target/openapi/ast/RequestBody.scala
  src/main/scala/temple/generate/target/openapi/ast/Response.scala
  src/main/scala/temple/generate/target/openapi/ast/Service.scala
  src/test/scala/temple/generate/target/openapi/OpenAPIGeneratorTest.scala
Labels: size/M

#135 [k8s-gen] Kubernetes Generator Integration Test
  docker/deploy.sh
  docker/shell2http.Dockerfile
  src/it/scala/temple/containers/DockerShell2HttpService.scala
  src/it/scala/temple/containers/KubeSpec.scala
  src/it/scala/temple/generate/kube/KubernetesGeneratorIntegrationTest.scala
  src/it/scala/temple/generate/kube/KubernetesGeneratorIntegrationTestData.scala
Labels: size/M

#137 [OpenAPI-gen] Lift parameters up a level as per spec changes
  src/main/scala/temple/generate/target/openapi/OpenAPIGenerator.scala
  src/main/scala/temple/generate/target/openapi/ast/Handler.scala
  src/main/scala/temple/generate/target/openapi/ast/OpenAPIFile.scala
  src/main/scala/temple/generate/target/openapi/ast/Path.scala
  src/test/scala/temple/generate/target/openapi/OpenAPIGeneratorTest.scala
Labels: size/M

#140 [go-gen] Add handlers and errors.go generation to auth
  src/main/resources/go/genFiles/auth/dao/errors.go.snippet
  src/main/resources/go/genFiles/auth/main/handlers.go.snippet
  src/main/scala/temple/generate/server/go/auth/GoAuthServiceDAOGenerator.scala
  src/main/scala/temple/generate/server/go/auth/GoAuthServiceGenerator.scala
  src/main/scala/temple/generate/server/go/service/GoServiceDAOGenerator.scala
  src/main/scala/temple/generate/server/go/service/GoServiceGenerator.scala
  src/test/scala/temple/generate/server/go/GoAuthServiceGeneratorTestData.scala
  src/test/scala/temple/generate/server/go/testfiles/auth/auth.go.snippet
  src/test/scala/temple/generate/server/go/testfiles/auth/dao/errors.go.snippet
Labels: size/L

#142 [semantics] Move Semantics AST to be shared across the whole Temple
  src/e2e/scala/temple/DSL/ParserE2ETest.scala
  src/it/scala/temple/generate/docker/DockerGeneratorIntegrationTest.scala
  src/it/scala/temple/generate/docker/DockerGeneratorIntegrationTestData.scala
  src/main/scala/temple/Application.scala
  src/main/scala/temple/DSL/semantics/Analyzer.scala
  src/main/scala/temple/DSL/semantics/ErrorHandling.scala
  src/main/scala/temple/DSL/semantics/MetadataParser.scala
  src/main/scala/temple/DSL/semantics/SemanticParsingException.scala
  src/main/scala/temple/ast/Annotation.scala
  src/main/scala/temple/ast/ArgMap.scala
  src/main/scala/temple/ast/ArgType.scala
  src/main/scala/temple/ast/Attribute.scala
  src/main/scala/temple/ast/AttributeType.scala
  src/main/scala/temple/ast/Metadata.scala
  src/main/scala/temple/ast/ProjectBlock.scala
  src/main/scala/temple/ast/ServiceBlock.scala
  src/main/scala/temple/ast/StructBlock.scala
  src/main/scala/temple/ast/TargetBlock.scala
  src/main/scala/temple/ast/TempleBlock.scala
  src/main/scala/temple/ast/Templefile.scala
  src/main/scala/temple/builder/DatabaseBuilder.scala
  src/main/scala/temple/builder/DockerfileBuilder.scala
  src/main/scala/temple/builder/project/ProjectBuilder.scala
  src/main/scala/temple/builder/project/ProjectConfig.scala
  src/main/scala/temple/generate/target/openapi/OpenAPIGenerator.scala
  src/main/scala/temple/generate/target/openapi/ast/Service.scala
  src/test/scala/temple/DSL/semantics/SemanticAnalyzerTest.scala
  src/test/scala/temple/DSL/semantics/TempleBlockTest.scala
  src/test/scala/temple/builder/BuilderTestData.scala
  src/test/scala/temple/builder/DockerfileBuilderTest.scala
  src/test/scala/temple/builder/project/ProjectBuilderTestData.scala
  src/test/scala/temple/generate/target/openapi/OpenAPIGeneratorTest.scala
Labels: size/L

#141 [OpenAPI-gen] Add Update and Delete endpoints
  src/main/scala/temple/generate/target/openapi/OpenAPIGenerator.scala
  src/main/scala/temple/generate/target/openapi/ast/Handler.scala
  src/main/scala/temple/generate/target/openapi/ast/Path.scala
  src/main/scala/temple/generate/target/openapi/ast/Service.scala
  src/test/scala/temple/generate/target/openapi/OpenAPIGeneratorTest.scala
Labels: size/L

#144 [syntax] Add SI prefix support to parser
  src/e2e/scala/temple/DSL/ParserE2ETest.scala
  src/e2e/scala/temple/SimpleE2ETestData.scala
  src/main/scala/temple/DSL/parser/DSLParser.scala
  src/test/scala/temple/DSL/parser/DSLParserTest.scala
  src/test/scala/temple/testfiles/simple.temple
Labels: size/S

#145 [openapi-gen] Add generate method for OpenAPI for consistency
  src/it/scala/temple/containers/GolangSpec.scala
  src/it/scala/temple/containers/KubeSpec.scala
  src/main/scala/temple/builder/project/Project.scala
  src/main/scala/temple/generate/FileSystem.scala
  src/main/scala/temple/generate/kube/KubernetesGenerator.scala
  src/main/scala/temple/generate/server/AuthServiceGenerator.scala
  src/main/scala/temple/generate/server/ServiceGenerator.scala
  src/main/scala/temple/generate/server/go/auth/GoAuthServiceGenerator.scala
  src/main/scala/temple/generate/server/go/service/GoServiceGenerator.scala
  src/main/scala/temple/generate/target/openapi/OpenAPIGenerator.scala
  src/test/scala/temple/generate/server/go/GoAuthServiceGeneratorTestData.scala
  src/test/scala/temple/generate/server/go/GoServiceGeneratorTestData.scala
  src/test/scala/temple/generate/target/openapi/OpenAPIGeneratorTest.scala
Labels: size/M

#143 [K8s-Gen] Kube Map
  src/e2e/resources/kube/kong/kong-db-deployment.yaml
  src/e2e/resources/kube/kong/kong-db-service.yaml
  src/e2e/resources/kube/kong/kong-deployment.yaml
  src/e2e/resources/kube/kong/kong-migration-job.yaml
  src/e2e/resources/kube/kong/kong-service.yaml
  src/e2e/scala/temple/SimpleE2ETest.scala
  src/e2e/scala/temple/SimpleE2ETestData.scala
  src/it/scala/temple/generate/kube/KubernetesGeneratorIntegrationTestData.scala
  src/main/scala/temple/ast/Templefile.scala
  src/main/scala/temple/builder/OrchestrationBuilder.scala
  src/main/scala/temple/builder/project/ProjectBuilder.scala
  src/main/scala/temple/builder/project/ProjectConfig.scala
  src/main/scala/temple/generate/kube/KubernetesGenerator.scala
  src/main/scala/temple/generate/kube/ast/OrchestrationType.scala
  src/main/scala/temple/utils/StringUtils.scala
  src/test/resources/kong/kong-db-deployment.yaml
  src/test/resources/kong/kong-db-service.yaml
  src/test/resources/kong/kong-deployment.yaml
  src/test/resources/kong/kong-migration-job.yaml
  src/test/resources/kong/kong-service.yaml
  src/test/scala/temple/builder/project/ProjectBuilderTest.scala
  src/test/scala/temple/builder/project/ProjectBuilderTestData.scala
  src/test/scala/temple/generate/kube/UnitTestData.scala
Labels: size/XL

#146 [grafana] Generate base grafana JSON
  src/main/scala/temple/generate/metrics/grafana/GrafanaDashboardGenerator.scala
  src/main/scala/temple/generate/metrics/grafana/ast/GrafanaRoot.scala
  src/main/scala/temple/generate/metrics/grafana/ast/Panel.scala
  src/main/scala/temple/utils/StringUtils.scala
  src/test/scala/temple/generate/metrics/grafana/GrafanaDashboardGeneratorTest.scala
  src/test/scala/temple/generate/metrics/grafana/GrafanaDashboardGeneratorTestData.scala
  src/test/scala/temple/utils/FileUtilsTest.scala
Labels: size/L

#147 [go-gen] Generate dao imports, interface and structs
  src/it/scala/temple/generate/docker/DockerGeneratorIntegrationTestData.scala
  src/it/scala/temple/generate/server/GoGeneratorIntegrationTestData.scala
  src/main/scala/temple/ast/AttributeType.scala
  src/main/scala/temple/generate/server/CreatedByAttribute.scala
  src/main/scala/temple/generate/server/IDAttribute.scala
  src/main/scala/temple/generate/server/ServiceRoot.scala
  src/main/scala/temple/generate/server/go/common/GoCommonDAOGenerator.scala
  src/main/scala/temple/generate/server/go/common/GoCommonGenerator.scala
  src/main/scala/temple/generate/server/go/service/GoServiceCommGenerator.scala
  src/main/scala/temple/generate/server/go/service/GoServiceDAOGenerator.scala
  src/main/scala/temple/generate/server/go/service/GoServiceGenerator.scala
  src/main/scala/temple/generate/server/go/service/GoServiceMainGenerator.scala
  src/main/scala/temple/generate/server/go/service/GoServiceUtilGenerator.scala
  src/main/scala/temple/generate/utils/CodeUtils.scala
  src/test/scala/temple/generate/server/go/GoServiceGeneratorTestData.scala
  src/test/scala/temple/generate/server/go/testfiles/match/dao/dao.go.snippet
  src/test/scala/temple/generate/server/go/testfiles/user/dao/dao.go.snippet
Labels: size/L

#148 [util] Move verb into the CRUD type
  src/main/scala/temple/generate/CRUD.scala
  src/main/scala/temple/generate/server/ServiceGenerator.scala
  src/main/scala/temple/generate/server/go/service/GoServiceDAOGenerator.scala
  src/main/scala/temple/generate/server/go/service/GoServiceMainGenerator.scala
Labels: size/M

#149 [grafana] Introduce new grafana types
  src/main/scala/temple/generate/metrics/grafana/GrafanaDashboardGenerator.scala
  src/main/scala/temple/generate/metrics/grafana/ast/GrafanaPanel.scala
  src/main/scala/temple/generate/metrics/grafana/ast/GrafanaRoot.scala
  src/main/scala/temple/generate/metrics/grafana/ast/GrafanaTarget.scala
  src/main/scala/temple/generate/metrics/grafana/ast/Panel.scala
  src/main/scala/temple/generate/metrics/grafana/ast/Row.scala
Labels: size/L

#150 [grafana] Grafana gen
  src/main/scala/temple/generate/metrics/grafana/GrafanaDashboardGenerator.scala
  src/main/scala/temple/generate/metrics/grafana/ast/GrafanaRoot.scala
  src/main/scala/temple/generate/metrics/grafana/ast/Row.scala
  src/test/scala/temple/generate/metrics/grafana/GrafanaDashboardGeneratorTest.scala
  src/test/scala/temple/generate/metrics/grafana/GrafanaDashboardGeneratorTestData.scala
  src/test/scala/temple/generate/metrics/grafana/GrafanaDashboardGeneratorTestUtils.scala
Labels: size/XL

#151 [semantics] Update Templefile with enumerable, readable & omit
  src/e2e/scala/temple/DSL/ParserE2ETest.scala
  src/main/scala/temple/DSL/semantics/Analyzer.scala
  src/main/scala/temple/DSL/semantics/MetadataParser.scala
  src/main/scala/temple/ast/Metadata.scala
  src/test/scala/temple/DSL/parser/DSLParserTest.scala
  src/test/scala/temple/testfiles/simple.temple
Labels: size/M

#157 [go-gen] Refactor dao generation
  src/it/scala/temple/generate/server/GoGeneratorIntegrationTestData.scala
  src/main/scala/temple/generate/server/CreatedByAttribute.scala
  src/main/scala/temple/generate/server/ServiceRoot.scala
  src/main/scala/temple/generate/server/go/service/GoServiceDAOGenerator.scala
  src/main/scala/temple/generate/server/go/service/GoServiceGenerator.scala
  src/test/scala/temple/generate/server/go/GoServiceGeneratorTestData.scala
Labels: size/L

#153 [Semantics] Parse Omit into set
  src/e2e/scala/temple/DSL/ParserE2ETest.scala
  src/main/scala/temple/ast/Metadata.scala
Labels: size/XS

#158 Grafana mapping
  src/e2e/resources/grafana/simple-templeuser.json
  src/e2e/scala/temple/SimpleE2ETest.scala
  src/e2e/scala/temple/SimpleE2ETestData.scala
  src/main/scala/temple/builder/MetricsBuilder.scala
  src/main/scala/temple/builder/project/ProjectBuilder.scala
  src/main/scala/temple/generate/metrics/grafana/GrafanaDashboardGenerator.scala
  src/main/scala/temple/generate/metrics/grafana/ast/GrafanaPanel.scala
  src/test/resources/grafana/complexuser.json
  src/test/resources/grafana/templeuser.json
  src/test/scala/temple/builder/project/ProjectBuilderTest.scala
  src/test/scala/temple/builder/project/ProjectBuilderTestData.scala
  src/test/scala/temple/generate/metrics/grafana/GrafanaDashboardGeneratorTestUtils.scala
Labels: size/XXL

#159 [go-gen] Add dao init and query function generation
  src/main/resources/go/genFiles/common/dao/init.go.snippet
  src/main/scala/temple/generate/server/go/common/GoCommonDAOGenerator.scala
  src/main/scala/temple/generate/server/go/service/GoServiceDAOGenerator.scala
  src/main/scala/temple/generate/server/go/service/GoServiceGenerator.scala
  src/test/scala/temple/generate/server/go/GoServiceGeneratorTest.scala
  src/test/scala/temple/generate/server/go/testfiles/match/dao/dao.go.snippet
  src/test/scala/temple/generate/server/go/testfiles/user/dao/dao.go.snippet
Labels: size/L

#154 [OpenAPI-gen] Add UUID type to OpenAPI
  src/main/scala/temple/generate/target/openapi/OpenAPIGenerator.scala
Labels: size/XS

#160 [grafana] Generate yml config for grafana
  src/main/scala/temple/generate/metrics/grafana/GrafanaDashboardConfigGenerator.scala
  src/main/scala/temple/generate/metrics/grafana/GrafanaDashboardGenerator.scala
  src/main/scala/temple/generate/metrics/grafana/ast/GrafanaDashboardConfig.scala
  src/test/scala/temple/generate/metrics/grafana/GrafanaDashboardConfigGeneratorTest.scala
  src/test/scala/temple/generate/metrics/grafana/GrafanaDashboardConfigGeneratorTestData.scala
Labels: size/M

#155 [Semantics] Use a context object for giving better errors
  src/main/scala/temple/DSL/semantics/Analyzer.scala
  src/main/scala/temple/DSL/semantics/ErrorHandling.scala
  src/main/scala/temple/DSL/semantics/MetadataParser.scala
  src/main/scala/temple/DSL/semantics/SemanticContext.scala
  src/main/scala/temple/DSL/semantics/SemanticParsingException.scala
  src/main/scala/temple/ast/ArgMap.scala
  src/main/scala/temple/ast/Metadata.scala
  src/main/scala/temple/collection/enumeration/Enum.scala
  src/main/scala/temple/collection/enumeration/EnumParser.scala
  src/main/scala/temple/errors/Context.scala
  src/main/scala/temple/errors/ErrorHandlingContext.scala
  src/main/scala/temple/errors/FailureContext.scala
  src/main/scala/temple/utils/MapUtils.scala
  src/test/scala/temple/DSL/semantics/SemanticAnalyzerTest.scala
  src/test/scala/temple/collection/enumeration/EnumTest.scala
  src/test/scala/temple/utils/MapUtilsTest.scala
Labels: size/L

#161 [gen] Rename ReadAll to List for consistency
  src/it/scala/temple/generate/server/GoGeneratorIntegrationTestData.scala
  src/main/scala/temple/builder/MetricsBuilder.scala
  src/main/scala/temple/builder/project/ProjectBuilder.scala
  src/main/scala/temple/generate/CRUD.scala
  src/main/scala/temple/generate/server/go/service/GoServiceDAOGenerator.scala
  src/main/scala/temple/generate/server/go/service/GoServiceMainGenerator.scala
  src/main/scala/temple/generate/target/openapi/OpenAPIGenerator.scala
  src/test/scala/temple/generate/server/go/GoServiceGeneratorTestData.scala
Labels: size/M

#163 [grafana] Output dashboard config
  src/e2e/scala/temple/SimpleE2ETest.scala
  src/e2e/scala/temple/SimpleE2ETestData.scala
  src/main/scala/temple/builder/project/ProjectBuilder.scala
  src/test/scala/temple/builder/project/ProjectBuilderTest.scala
  src/test/scala/temple/builder/project/ProjectBuilderTestData.scala
Labels: size/M

#167 [go-gen] Add CodeTermNone
  src/main/scala/temple/generate/utils/CodeTerm.scala
Labels: size/XS

#166 [go-gen] Add prefix command
  src/main/scala/temple/generate/utils/CodeTerm.scala
Labels: size/XS

#164 [grafana] Use custom type for datasource
  src/main/scala/temple/builder/MetricsBuilder.scala
  src/main/scala/temple/builder/project/ProjectBuilder.scala
  src/main/scala/temple/generate/metrics/grafana/GrafanaDashboardConfigGenerator.scala
  src/main/scala/temple/generate/metrics/grafana/ast/Datasource.scala
  src/main/scala/temple/generate/metrics/grafana/ast/GrafanaDashboardConfig.scala
  src/main/scala/temple/generate/metrics/grafana/ast/GrafanaPanel.scala
  src/main/scala/temple/generate/metrics/grafana/ast/Row.scala
  src/test/scala/temple/generate/metrics/grafana/GrafanaDashboardConfigGeneratorTest.scala
  src/test/scala/temple/generate/metrics/grafana/GrafanaDashboardGeneratorTest.scala
Labels: size/L

#168 [gen] Add tests for CodeTerm
  src/main/scala/temple/generate/utils/CodeTerm.scala
  src/test/scala/temple/generate/utils/CodeTermTest.scala
Labels: size/S

#169 [go-gen] Add dao list interface function generation
  src/it/scala/temple/generate/server/GoGeneratorIntegrationTestData.scala
  src/main/scala/temple/generate/database/DatabaseGenerator.scala
  src/main/scala/temple/generate/database/PostgresGenerator.scala
  src/main/scala/temple/generate/server/ServiceGenerator.scala
  src/main/scala/temple/generate/server/ServiceRoot.scala
  src/main/scala/temple/generate/server/go/common/GoCommonDAOGenerator.scala
  src/main/scala/temple/generate/server/go/common/GoCommonGenerator.scala
  src/main/scala/temple/generate/server/go/service/GoServiceDAOGenerator.scala
  src/main/scala/temple/generate/server/go/service/GoServiceGenerator.scala
  src/test/scala/temple/generate/server/go/GoServiceGeneratorTest.scala
  src/test/scala/temple/generate/server/go/GoServiceGeneratorTestData.scala
  src/test/scala/temple/generate/server/go/testfiles/match/dao/dao.go.snippet
  src/test/scala/temple/generate/server/go/testfiles/user/dao/dao.go.snippet
Labels: size/L

#171 [sql-gen] Support UUID type in postgres
  src/e2e/scala/temple/SimpleE2ETestData.scala
  src/it/scala/temple/containers/PostgresSpec.scala
  src/it/scala/temple/generate/database/PostgresGeneratorIntegrationTest.scala
  src/it/scala/temple/generate/database/PreparedVariable.scala
  src/it/scala/temple/generate/database/TestData.scala
  src/main/scala/temple/builder/DatabaseBuilder.scala
  src/main/scala/temple/generate/database/PostgresGenerator.scala
  src/main/scala/temple/generate/database/ast/ColType.scala
  src/test/scala/temple/generate/database/PostgresGeneratorTestData.scala
Labels: size/M

#172 [go-gen] Refactor dao generation
  src/main/scala/temple/generate/server/go/service/GoServiceDAOGenerator.scala
  src/main/scala/temple/generate/server/go/service/GoServiceGenerator.scala
  src/main/scala/temple/generate/server/go/service/dao/GoServiceDAOFunctionsGenerator.scala
  src/main/scala/temple/generate/server/go/service/dao/GoServiceDAOGenerator.scala
  src/main/scala/temple/generate/server/go/service/dao/GoServiceDAOInputStructsGenerator.scala
  src/main/scala/temple/generate/server/go/service/dao/GoServiceDAOInterfaceGenerator.scala
  src/main/scala/temple/generate/server/go/service/dao/GoServiceDAOListFunctionGenerator.scala
Labels: size/XL

#173 [sql-gen] Support returning in insert and update queries
  src/it/scala/temple/containers/PostgresSpec.scala
  src/it/scala/temple/generate/database/PostgresGeneratorIntegrationTest.scala
  src/it/scala/temple/generate/database/TestData.scala
  src/main/scala/temple/generate/database/PostgresGenerator.scala
  src/main/scala/temple/generate/database/ast/Statement.scala
  src/test/scala/temple/generate/database/PostgresGeneratorTest.scala
  src/test/scala/temple/generate/database/PostgresGeneratorTestData.scala
Labels: size/L

#170 [grafana] Generate datasource YML for Grafana
  src/main/scala/temple/builder/project/ProjectBuilder.scala
  src/main/scala/temple/generate/metrics/grafana/GrafanaDatasourceConfigGenerator.scala
  src/main/scala/temple/generate/metrics/grafana/ast/Datasource.scala
  src/main/scala/temple/generate/metrics/grafana/ast/GrafanaDatasourceConfig.scala
  src/test/scala/temple/generate/metrics/grafana/GrafanaDashboardConfigGeneratorTest.scala
  src/test/scala/temple/generate/metrics/grafana/GrafanaDashboardGeneratorTest.scala
  src/test/scala/temple/generate/metrics/grafana/GrafanaDatasourceConfigGeneratorTest.scala
  src/test/scala/temple/generate/metrics/grafana/GrafanaDatasourceConfigGeneratorTestData.scala
Labels: size/L

#165 [Application] Implement question asking functionality and details
  src/main/scala/temple/detail/LanguageDetail.scala
  src/main/scala/temple/detail/LanguageSpecificDetailBuilder.scala
  src/main/scala/temple/detail/PoliceSergeantNicholasAngel.scala
  src/main/scala/temple/detail/QuestionAsker.scala
  src/test/scala/temple/detail/LanguageSpecificDetailBuilderTest.scala
  src/test/scala/temple/detail/LanguageSpecificDetailBuilderTestData.scala
  src/test/scala/temple/detail/MockQuestionAsker.scala
Labels: size/L

#162 [gen] Make CRUD a simple enum
  src/main/scala/temple/builder/MetricsBuilder.scala
  src/main/scala/temple/generate/CRUD.scala
  src/main/scala/temple/generate/server/ServiceRoot.scala
  src/main/scala/temple/generate/server/go/service/GoServiceMainGenerator.scala
  src/main/scala/temple/generate/server/go/service/dao/GoServiceDAOFunctionsGenerator.scala
  src/main/scala/temple/generate/server/go/service/dao/GoServiceDAOGenerator.scala
  src/main/scala/temple/generate/server/go/service/dao/GoServiceDAOInputStructsGenerator.scala
  src/main/scala/temple/generate/server/go/service/dao/GoServiceDAOInterfaceGenerator.scala
  src/main/scala/temple/generate/target/openapi/ast/Service.scala
Labels: size/M

#174 [sql-gen] Support prepared statements in update and where
  src/it/scala/temple/generate/database/PostgresGeneratorIntegrationTest.scala
  src/it/scala/temple/generate/database/TestData.scala
  src/main/scala/temple/generate/database/PostgresGenerator.scala
  src/main/scala/temple/generate/database/ast/Condition.scala
  src/main/scala/temple/generate/database/ast/Expression.scala
  src/test/scala/temple/generate/database/PostgresGeneratorTest.scala
  src/test/scala/temple/generate/database/PostgresGeneratorTestData.scala
Labels: size/L

#175 [sql-gen] Allow arguments to be preprovided to the insert query
  src/it/scala/temple/generate/database/PostgresGeneratorIntegrationTest.scala
  src/it/scala/temple/generate/database/TestData.scala
  src/main/scala/temple/generate/database/PostgresGenerator.scala
  src/main/scala/temple/generate/database/ast/Statement.scala
  src/test/scala/temple/generate/database/PostgresGeneratorTest.scala
  src/test/scala/temple/generate/database/PostgresGeneratorTestData.scala
Labels: size/L

#177 [go-gen] Generate dao function bodies
  src/main/scala/temple/generate/server/IDAttribute.scala
  src/main/scala/temple/generate/server/go/common/GoCommonGenerator.scala
  src/main/scala/temple/generate/server/go/service/dao/GoServiceDAOFunctionsGenerator.scala
  src/main/scala/temple/generate/server/go/service/dao/GoServiceDAOGenerator.scala
  src/main/scala/temple/generate/server/go/service/dao/GoServiceDAOListFunctionGenerator.scala
  src/main/scala/temple/generate/utils/CodeTerm.scala
  src/test/scala/temple/generate/server/go/testfiles/match/dao/dao.go.snippet
  src/test/scala/temple/generate/server/go/testfiles/match/dao/errors.go.snippet
  src/test/scala/temple/generate/server/go/testfiles/user/dao/dao.go.snippet
  src/test/scala/temple/generate/server/go/testfiles/user/dao/errors.go.snippet
Labels: size/L

#176 [grafana] Add datasource config to mapping
  src/e2e/scala/temple/SimpleE2ETest.scala
  src/e2e/scala/temple/SimpleE2ETestData.scala
  src/main/scala/temple/builder/project/ProjectBuilder.scala
  src/test/scala/temple/builder/project/ProjectBuilderTest.scala
  src/test/scala/temple/builder/project/ProjectBuilderTestData.scala
Labels: size/M

#178 [prom] Add prometheus config generator
  src/main/scala/temple/DSL/semantics/Analyzer.scala
  src/main/scala/temple/ast/ArgMap.scala
  src/main/scala/temple/builder/MetricsBuilder.scala
  src/main/scala/temple/builder/project/ProjectBuilder.scala
  src/main/scala/temple/generate/metrics/grafana/GrafanaDashboardConfigGenerator.scala
  src/main/scala/temple/generate/metrics/prometheus/PrometheusConfigGenerator.scala
  src/main/scala/temple/generate/metrics/prometheus/ast/PrometheusConfig.scala
  src/main/scala/temple/generate/metrics/prometheus/ast/PrometheusJob.scala
  src/main/scala/temple/generate/server/ServiceRoot.scala
  src/main/scala/temple/generate/target/openapi/OpenAPIGenerator.scala
  src/main/scala/temple/generate/target/openapi/ast/OpenAPIFile.scala
  src/main/scala/temple/utils/FileUtils.scala
  src/test/scala/temple/DSL/semantics/SemanticAnalyzerTest.scala
  src/test/scala/temple/DSL/semantics/TempleBlockTest.scala
  src/test/scala/temple/builder/DockerfileBuilderTestData.scala
  src/test/scala/temple/generate/metrics/grafana/GrafanaDashboardGeneratorTest.scala
  src/test/scala/temple/generate/metrics/prometheus/PrometheusConfigGeneratorTest.scala
  src/test/scala/temple/generate/metrics/prometheus/PrometheusConfigGeneratorTestData.scala
  src/test/scala/temple/utils/StringUtilsTest.scala
Labels: size/M

#156 [Semantics] Add Templefile validator
  src/e2e/scala/temple/DSL/ParserE2ETest.scala
  src/e2e/scala/temple/SimpleE2ETest.scala
  src/e2e/scala/temple/SimpleE2ETestData.scala
  src/main/scala/temple/Application.scala
  src/main/scala/temple/DSL/semantics/Analyzer.scala
  src/main/scala/temple/DSL/semantics/SemanticContext.scala
  src/main/scala/temple/DSL/semantics/Validator.scala
  src/main/scala/temple/DSL/syntax/Arg.scala
  src/main/scala/temple/DSL/syntax/Args.scala
  src/main/scala/temple/DSL/syntax/Entry.scala
  src/main/scala/temple/ast/Annotation.scala
  src/main/scala/temple/ast/ArgMap.scala
  src/main/scala/temple/ast/Metadata.scala
  src/main/scala/temple/ast/Templefile.scala
  src/main/scala/temple/errors/Context.scala
  src/main/scala/temple/utils/MonadUtils.scala
  src/test/scala/temple/DSL/parser/DSLParserTest.scala
  src/test/scala/temple/DSL/semantics/SemanticAnalyzerTest.scala
  src/test/scala/temple/DSL/semantics/TempleBlockTest.scala
  src/test/scala/temple/DSL/semantics/ValidatorTest.scala
  src/test/scala/temple/builder/DockerfileBuilderTest.scala
  src/test/scala/temple/builder/project/ProjectBuilderTestData.scala
  src/test/scala/temple/detail/LanguageSpecificDetailBuilderTestData.scala
  src/test/scala/temple/testfiles/simple.temple
Labels: size/L

#179 [go-gen] Refactor to pass around service root rather than deconstructing
  src/main/scala/temple/generate/server/go/auth/GoAuthServiceCommGenerator.scala
  src/main/scala/temple/generate/server/go/auth/GoAuthServiceGenerator.scala
  src/main/scala/temple/generate/server/go/auth/GoAuthServiceMainGenerator.scala
  src/main/scala/temple/generate/server/go/common/GoCommonGenerator.scala
  src/main/scala/temple/generate/server/go/service/GoServiceCommGenerator.scala
  src/main/scala/temple/generate/server/go/service/GoServiceGenerator.scala
  src/main/scala/temple/generate/server/go/service/GoServiceMainGenerator.scala
  src/main/scala/temple/generate/server/go/service/dao/GoServiceDAOFunctionsGenerator.scala
  src/main/scala/temple/generate/server/go/service/dao/GoServiceDAOGenerator.scala
  src/main/scala/temple/generate/server/go/service/dao/GoServiceDAOInputStructsGenerator.scala
  src/main/scala/temple/generate/server/go/service/dao/GoServiceDAOInterfaceGenerator.scala
Labels: size/L

#181 [fmt] Format multiline strings correctly
  .scalafmt.conf
  src/test/scala/temple/generate/database/PostgresGeneratorTestData.scala
Labels: size/M

#180 [prom] Map into prometheus configuration generator
  src/e2e/scala/temple/SimpleE2ETest.scala
  src/e2e/scala/temple/SimpleE2ETestData.scala
  src/main/scala/temple/ast/Templefile.scala
  src/main/scala/temple/builder/project/ProjectBuilder.scala
  src/test/scala/temple/builder/project/ProjectBuilderTest.scala
  src/test/scala/temple/builder/project/ProjectBuilderTestData.scala
Labels: size/M

#182 [semantics] Add temple validate command
  src/main/scala/temple/Application.scala
  src/main/scala/temple/Main.scala
  src/main/scala/temple/TempleConfig.scala
  src/test/scala/temple/testfiles/badSemantics.temple
  src/test/scala/temple/testfiles/badSyntax.temple
  src/test/scala/temple/testfiles/badValidation.temple
Labels: size/M

#184 [endpoint-test] Add test CLI mode
  src/main/scala/temple/Application.scala
  src/main/scala/temple/Main.scala
  src/main/scala/temple/TempleConfig.scala
  src/main/scala/temple/test/EndpointTester.scala
Labels: size/S

#183 [cmd] Take input from stdin
  src/main/scala/temple/Application.scala
  src/main/scala/temple/TempleConfig.scala
  src/main/scala/temple/utils/FileUtils.scala
Labels: size/M

#185 [go-gen] Generate auth dao.go
  src/main/resources/go/genFiles/auth/dao/errors.go.snippet
  src/main/scala/temple/generate/server/AuthAttribute.scala
  src/main/scala/temple/generate/server/AuthServiceRoot.scala
  src/main/scala/temple/generate/server/go/auth/GoAuthServiceDAOGenerator.scala
  src/main/scala/temple/generate/server/go/auth/GoAuthServiceGenerator.scala
  src/main/scala/temple/generate/server/go/common/GoCommonGenerator.scala
  src/main/scala/temple/generate/server/go/service/dao/GoServiceDAOFunctionsGenerator.scala
  src/test/scala/temple/generate/server/go/GoAuthServiceGeneratorTestData.scala
  src/test/scala/temple/generate/server/go/testfiles/auth/dao/dao.go.snippet
  src/test/scala/temple/generate/server/go/testfiles/auth/dao/errors.go.snippet
Labels: size/L

#187 [go-gen] Add non-auth handler.go generation
  src/main/resources/go/genFiles/common/comm/init.go.snippet
  src/main/scala/temple/generate/server/ServiceRoot.scala
  src/main/scala/temple/generate/server/go/auth/GoAuthServiceGenerator.scala
  src/main/scala/temple/generate/server/go/common/GoCommonCommGenerator.scala
  src/main/scala/temple/generate/server/go/common/GoCommonGenerator.scala
  src/main/scala/temple/generate/server/go/service/GoServiceCommGenerator.scala
  src/main/scala/temple/generate/server/go/service/GoServiceGenerator.scala
  src/test/scala/temple/generate/server/go/testfiles/match/comm/handler.go.snippet
Labels: size/L

#188 [endpoint-test] Spin up Kube infra, perform sample request and shut down
  build.sbt
  src/main/scala/temple/Application.scala
  src/main/scala/temple/test/EndpointTester.scala
  src/main/scala/temple/test/ProjectTester.scala
  src/main/scala/temple/test/internal/EndpointConfig.scala
Labels: size/M

#189 [project-test] Add Auth Service Tests
  src/main/scala/temple/test/ProjectTester.scala
  src/main/scala/temple/test/internal/AuthServiceTest.scala
  src/main/scala/temple/test/internal/EndpointConfig.scala
  src/main/scala/temple/test/internal/EndpointTest.scala
  src/main/scala/temple/test/internal/ProjectConfig.scala
  src/main/scala/temple/test/internal/ServiceTest.scala
  src/main/scala/temple/test/internal/ServiceTestUtils.scala
Labels: size/L

#190 [Builder] Open endpoint generation code to be public
  src/main/scala/temple/builder/project/ProjectBuilder.scala
Labels: size/XS

#191 [Go-Map] Build go level SQL statements
  src/main/scala/temple/ast/ServiceBlock.scala
  src/main/scala/temple/builder/DatabaseBuilder.scala
  src/main/scala/temple/generate/database/ast/Assignment.scala
  src/test/scala/temple/builder/DatabaseBuilderTest.scala
  src/test/scala/temple/builder/DatabaseBuilderTestData.scala
Labels: size/L

#194 Service tester crud
  src/main/scala/temple/test/ProjectTester.scala
  src/main/scala/temple/test/internal/AuthServiceTest.scala
  src/main/scala/temple/test/internal/CRUDServiceTest.scala
  src/main/scala/temple/test/internal/EndpointTest.scala
  src/main/scala/temple/test/internal/ServiceTestUtils.scala
Labels: size/L

#193 [Go-Map] Server Builder
  src/main/scala/temple/ast/ServiceBlock.scala
  src/main/scala/temple/builder/ServerBuilder.scala
  src/main/scala/temple/builder/project/LanguageConfig.scala
  src/test/scala/temple/builder/BuilderTestData.scala
  src/test/scala/temple/builder/ServerBuilderTest.scala
Labels: size/L

#195 [go-gen] Update go main file import generation
  src/main/scala/temple/generate/server/go/service/GoServiceGenerator.scala
  src/main/scala/temple/generate/server/go/service/GoServiceMainGenerator.scala
  src/main/scala/temple/generate/server/go/service/dao/GoServiceDAOGenerator.scala
  src/test/scala/temple/generate/server/go/testfiles/match/match.go.snippet
  src/test/scala/temple/generate/server/go/testfiles/user/user.go.snippet
Labels: size/L

#197 [project-test] Add tests for read, update and delete endpoints
  src/main/scala/temple/test/internal/CRUDServiceTest.scala
  src/main/scala/temple/test/internal/EndpointTest.scala
  src/main/scala/temple/test/internal/ServiceTestUtils.scala
Labels: size/L

#198 [go-gen] Remove attribute type from IDAttribute and CreatedByAttribute
  src/it/scala/temple/generate/server/GoGeneratorIntegrationTestData.scala
  src/main/scala/temple/builder/DatabaseBuilder.scala
  src/main/scala/temple/builder/ServerBuilder.scala
  src/main/scala/temple/generate/server/CreatedByAttribute.scala
  src/main/scala/temple/generate/server/IDAttribute.scala
  src/main/scala/temple/generate/server/ServiceRoot.scala
  src/main/scala/temple/generate/server/go/auth/GoAuthServiceDAOGenerator.scala
  src/main/scala/temple/generate/server/go/service/GoServiceCommGenerator.scala
  src/main/scala/temple/generate/server/go/service/dao/GoServiceDAOFunctionsGenerator.scala
  src/main/scala/temple/generate/server/go/service/dao/GoServiceDAOGenerator.scala
  src/main/scala/temple/generate/server/go/service/dao/GoServiceDAOInputStructsGenerator.scala
  src/test/scala/temple/builder/DatabaseBuilderTest.scala
  src/test/scala/temple/builder/ServerBuilderTest.scala
  src/test/scala/temple/generate/server/go/GoAuthServiceGeneratorTestData.scala
  src/test/scala/temple/generate/server/go/GoServiceGeneratorTestData.scala
Labels: size/M

#199 [Go-Map] Update ProjectBuilder & Tests 2: Electric Boogalloo
  build.sbt
  src/e2e/scala/temple/SimpleE2ETest.scala
  src/main/scala/temple/Application.scala
  src/main/scala/temple/Main.scala
  src/main/scala/temple/builder/project/ProjectBuilder.scala
  src/test/resources/go/complex-user/complexuser.go.snippet
  src/test/resources/go/complex-user/dao/dao.go.snippet
  src/test/resources/go/complex-user/dao/errors.go.snippet
  src/test/resources/go/complex-user/go.mod.snippet
  src/test/resources/go/complex-user/util/util.go.snippet
  src/test/resources/go/simple-user/dao/dao.go.snippet
  src/test/resources/go/simple-user/dao/errors.go.snippet
  src/test/resources/go/simple-user/go.mod.snippet
  src/test/resources/go/simple-user/user.go.snippet
  src/test/resources/go/simple-user/util/util.go.snippet
  src/test/scala/temple/builder/project/ProjectBuilderTest.scala
  src/test/scala/temple/builder/project/ProjectBuilderTestData.scala
Labels: size/XL

#192 [Builder] Add a builder for the OpenAPI generation
  src/e2e/scala/temple/SimpleE2ETest.scala
  src/main/scala/temple/ast/Metadata.scala
  src/main/scala/temple/ast/ServiceBlock.scala
  src/main/scala/temple/ast/StructBlock.scala
  src/main/scala/temple/ast/TempleBlock.scala
  src/main/scala/temple/builder/OpenAPIBuilder.scala
  src/main/scala/temple/builder/project/ProjectBuilder.scala
  src/main/scala/temple/generate/target/openapi/OpenAPIGenerator.scala
  src/main/scala/temple/generate/target/openapi/ast/OpenAPIRoot.scala
  src/main/scala/temple/generate/target/openapi/ast/Service.scala
  src/test/scala/temple/builder/project/ProjectBuilderTest.scala
  src/test/scala/temple/builder/project/ProjectBuilderTestData.scala
  src/test/scala/temple/generate/target/openapi/OpenAPIGeneratorTest.scala
Labels: size/XL

#200 [Go-Map] End to End tests
  src/e2e/resources/go/user/dao/dao.go.snippet
  src/e2e/resources/go/user/dao/errors.go.snippet
  src/e2e/resources/go/user/go.mod.snippet
  src/e2e/resources/go/user/user.go.snippet
  src/e2e/resources/go/user/util/util.go.snippet
  src/e2e/scala/temple/SimpleE2ETest.scala
Labels: size/L

#202 [fix] Map foreign keys to uuid types in server builder
  src/main/scala/temple/builder/ServerBuilder.scala
Labels: size/XS

#204 [go-gen] Add main.go request struct generation
  src/e2e/resources/go/user/user.go.snippet
  src/main/scala/temple/generate/server/go/common/GoCommonGenerator.scala
  src/main/scala/temple/generate/server/go/service/GoServiceGenerator.scala
  src/main/scala/temple/generate/server/go/service/GoServiceMainGenerator.scala
  src/main/scala/temple/generate/utils/CodeUtils.scala
  src/test/resources/go/complex-user/complexuser.go.snippet
  src/test/resources/go/simple-user/user.go.snippet
  src/test/scala/temple/generate/server/go/GoServiceGeneratorTestData.scala
  src/test/scala/temple/generate/server/go/testfiles/match/match.go.snippet
  src/test/scala/temple/generate/server/go/testfiles/user/user.go.snippet
Labels: size/L

#201 [Misc] Transfer Nicholas Angle into the country somewhere
  src/e2e/scala/temple/SimpleE2ETest.scala
  src/main/scala/temple/Main.scala
  src/main/scala/temple/detail/StdInQuestionAsker.scala
  src/test/scala/temple/detail/LanguageSpecificDetailBuilderTest.scala
  src/test/scala/temple/detail/MockQuestionAsker.scala
  src/test/scala/temple/detail/PoliceSergeantNicholasAngel.scala
Labels: size/M

#205 [Validator] Test sets of errors rather than strings
  src/main/scala/temple/DSL/semantics/Validator.scala
  src/test/scala/temple/DSL/semantics/ValidatorTest.scala
Labels: size/L
